- name: Reset root password
  become: true
  ansible.builtin.shell: set -o pipefail && echo "root:$(pwgen 32 1)" | chpasswd
  args:
    executable: /usr/bin/bash
  changed_when: false

- name: Reset current user's password
  become: true
  ansible.builtin.shell: set -o pipefail && echo "{{ ansible_user }}:$(pwgen 32 1)" | chpasswd
  args:
    executable: /usr/bin/bash
  changed_when: false
  when: ansible_user != 'root'
