[program:minio]
command=/usr/bin/minio server /var/lib/minio/data --console-address :9001
autostart=true
user=root
autorestart=true
loglevel=info
environment=MINIO_ROOT_USER=admin,MINIO_ROOT_PASSWORD=12345678

