syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.github.saturn_xiv.palm.plugins.portal.v1";
option java_outer_classname = "PortalProto";
option go_package = "./;v2";
option csharp_namespace = "Palm.Plugins.Portal.Grpc";
package palm.portal.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";

// ----------------------------------------------------------------------------

message IdRequest {
  int64 id = 1;
}

message Page {
  int64 index = 1;
  int64 size  = 2;
}

message Pagination {
  Page  current      = 1;
  bool  has_previous = 2;
  bool  has_next     = 3;
  int64 pages        = 4;
  int64 total        = 5;
}

message File  {
  string bucket = 1;
  string object = 2;
}

message RichText {
  enum Editor {
    CK_EDITOR = 0;
  }
  Editor        editor      = 1;
  string        body        = 2;
  repeated File attachments = 3;
}

message Location {
  enum Map {
    GOOGLE = 0;
  }
  Map    map     = 1;
  string address = 2;
}

// ----------------------------------------------------------------------------

service User {
}

message HashedPassword {
  bytes data = 1;
  bytes salt = 2;
}

message UserIndexResponse{
  message Item{
    enum Type{
      Email             = 0;
      Sms               = 1;
      GoogleOauth2      = 2;
      WechatOauth2      = 3;
      WechatMiniProgram = 4;
    }
    int64  id   = 1;
    Type   type = 2;
    string sn   = 3;
  }
  repeated Item items      = 1;
  Pagination    pagination = 9;
}

message Session {
  string                    locale     = 1;
  optional string           client_ip  = 2;
  google.protobuf.Timestamp created_at = 99;
}
// ----------------------------------------------------------------------------

service Site {
  rpc Heartbeat(google.protobuf.Empty) returns (SiteHeartbeatResponse) {}
}

message SiteHeartbeatResponse{
  optional string db    = 1;
  optional string cache = 2;
  optional string queue = 3;
  optional string s3    = 4;

  string                    version    = 98;
  google.protobuf.Timestamp created_at = 99;
}
