add_rules("mode.debug", "mode.release")
set_version("2026.3.26", {build = "%a %b %d %I:%M:%S %p %Z %Y"})  

add_requires("cpr", "nlohmann_json")
add_requires("boost", {system = false, configs = {cmake = false, asio=true, program_options=true, log=true, log_setup=true, exception=true}})

target("atropa")
    set_languages("c++23")
    set_kind("binary")
    add_ldflags("-static -static-libgcc -static-libstdc++")
    set_configdir("$(builddir)/$(plat)/$(arch)/$(mode)")
    add_configfiles("include/palm/version.h.in", {filename = "include/palm/version.hpp"})
    add_files("src/*.cpp")
    add_includedirs("include", "$(builddir)/$(plat)/$(arch)/$(mode)/include")    
    add_packages("boost", "cpr", "nlohmann_json")
