[program:seaweedfs]
command=/usr/local/bin/weed weed mini -dir=.
autostart=true
autorestart=true
user=nobody
directory=/var/lib/seaweedfs
environment=AWS_ACCESS_KEY_ID="www",AWS_SECRET_ACCESS_KEY="change-me",S3_BUCKET="default",MINIO_ROOT_PASSWORD="12345678"
