[package]
name = "bamboo"
version = "2025.11.2"
edition = "2024"
description = "A smart router system based on Linux operating system targeting embedded devices."

[dependencies]
env_logger = "0.11"
clap = "4"

[dependencies.diesel]
version = "2"
default-features = false
features = ["sqlite", "extras", "huge-tables"]

[dependencies.phlox]
path = "../phlox"
