// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: monitoring.proto

#include "monitoring.pb.h"
#include "monitoring.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace palm {
namespace monitoring {
namespace v1 {

static const char* Site_method_names[] = {
  "/palm.monitoring.v1.Site/Layout",
};

std::unique_ptr< Site::Stub> Site::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Site::Stub> stub(new Site::Stub(channel, options));
  return stub;
}

Site::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Layout_(Site_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Site::Stub::Layout(::grpc::ClientContext* context, const ::palm::monitoring::v1::SiteLayoutRequest& request, ::palm::monitoring::v1::SiteLayoutResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::monitoring::v1::SiteLayoutRequest, ::palm::monitoring::v1::SiteLayoutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Layout_, context, request, response);
}

void Site::Stub::async::Layout(::grpc::ClientContext* context, const ::palm::monitoring::v1::SiteLayoutRequest* request, ::palm::monitoring::v1::SiteLayoutResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::monitoring::v1::SiteLayoutRequest, ::palm::monitoring::v1::SiteLayoutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Layout_, context, request, response, std::move(f));
}

void Site::Stub::async::Layout(::grpc::ClientContext* context, const ::palm::monitoring::v1::SiteLayoutRequest* request, ::palm::monitoring::v1::SiteLayoutResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Layout_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::SiteLayoutResponse>* Site::Stub::PrepareAsyncLayoutRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::SiteLayoutRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::monitoring::v1::SiteLayoutResponse, ::palm::monitoring::v1::SiteLayoutRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Layout_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::SiteLayoutResponse>* Site::Stub::AsyncLayoutRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::SiteLayoutRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLayoutRaw(context, request, cq);
  result->StartCall();
  return result;
}

Site::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Site_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Site::Service, ::palm::monitoring::v1::SiteLayoutRequest, ::palm::monitoring::v1::SiteLayoutResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Site::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::monitoring::v1::SiteLayoutRequest* req,
             ::palm::monitoring::v1::SiteLayoutResponse* resp) {
               return service->Layout(ctx, req, resp);
             }, this)));
}

Site::Service::~Service() {
}

::grpc::Status Site::Service::Layout(::grpc::ServerContext* context, const ::palm::monitoring::v1::SiteLayoutRequest* request, ::palm::monitoring::v1::SiteLayoutResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* Systemd_method_names[] = {
  "/palm.monitoring.v1.Systemd/Journal",
};

std::unique_ptr< Systemd::Stub> Systemd::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Systemd::Stub> stub(new Systemd::Stub(channel, options));
  return stub;
}

Systemd::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Journal_(Systemd_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Systemd::Stub::Journal(::grpc::ClientContext* context, const ::palm::monitoring::v1::SystemdJournalRequest& request, ::palm::monitoring::v1::SystemdJournalResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::monitoring::v1::SystemdJournalRequest, ::palm::monitoring::v1::SystemdJournalResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Journal_, context, request, response);
}

void Systemd::Stub::async::Journal(::grpc::ClientContext* context, const ::palm::monitoring::v1::SystemdJournalRequest* request, ::palm::monitoring::v1::SystemdJournalResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::monitoring::v1::SystemdJournalRequest, ::palm::monitoring::v1::SystemdJournalResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Journal_, context, request, response, std::move(f));
}

void Systemd::Stub::async::Journal(::grpc::ClientContext* context, const ::palm::monitoring::v1::SystemdJournalRequest* request, ::palm::monitoring::v1::SystemdJournalResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Journal_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::SystemdJournalResponse>* Systemd::Stub::PrepareAsyncJournalRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::SystemdJournalRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::monitoring::v1::SystemdJournalResponse, ::palm::monitoring::v1::SystemdJournalRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Journal_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::SystemdJournalResponse>* Systemd::Stub::AsyncJournalRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::SystemdJournalRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncJournalRaw(context, request, cq);
  result->StartCall();
  return result;
}

Systemd::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Systemd_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Systemd::Service, ::palm::monitoring::v1::SystemdJournalRequest, ::palm::monitoring::v1::SystemdJournalResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Systemd::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::monitoring::v1::SystemdJournalRequest* req,
             ::palm::monitoring::v1::SystemdJournalResponse* resp) {
               return service->Journal(ctx, req, resp);
             }, this)));
}

Systemd::Service::~Service() {
}

::grpc::Status Systemd::Service::Journal(::grpc::ServerContext* context, const ::palm::monitoring::v1::SystemdJournalRequest* request, ::palm::monitoring::v1::SystemdJournalResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* FileSystem_method_names[] = {
  "/palm.monitoring.v1.FileSystem/Logs",
};

std::unique_ptr< FileSystem::Stub> FileSystem::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< FileSystem::Stub> stub(new FileSystem::Stub(channel, options));
  return stub;
}

FileSystem::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Logs_(FileSystem_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status FileSystem::Stub::Logs(::grpc::ClientContext* context, const ::palm::monitoring::v1::FileSystemLogsRequest& request, ::palm::monitoring::v1::FileSystemLogsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::monitoring::v1::FileSystemLogsRequest, ::palm::monitoring::v1::FileSystemLogsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Logs_, context, request, response);
}

void FileSystem::Stub::async::Logs(::grpc::ClientContext* context, const ::palm::monitoring::v1::FileSystemLogsRequest* request, ::palm::monitoring::v1::FileSystemLogsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::monitoring::v1::FileSystemLogsRequest, ::palm::monitoring::v1::FileSystemLogsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Logs_, context, request, response, std::move(f));
}

void FileSystem::Stub::async::Logs(::grpc::ClientContext* context, const ::palm::monitoring::v1::FileSystemLogsRequest* request, ::palm::monitoring::v1::FileSystemLogsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Logs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::FileSystemLogsResponse>* FileSystem::Stub::PrepareAsyncLogsRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::FileSystemLogsRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::monitoring::v1::FileSystemLogsResponse, ::palm::monitoring::v1::FileSystemLogsRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Logs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::FileSystemLogsResponse>* FileSystem::Stub::AsyncLogsRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::FileSystemLogsRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLogsRaw(context, request, cq);
  result->StartCall();
  return result;
}

FileSystem::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      FileSystem_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< FileSystem::Service, ::palm::monitoring::v1::FileSystemLogsRequest, ::palm::monitoring::v1::FileSystemLogsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](FileSystem::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::monitoring::v1::FileSystemLogsRequest* req,
             ::palm::monitoring::v1::FileSystemLogsResponse* resp) {
               return service->Logs(ctx, req, resp);
             }, this)));
}

FileSystem::Service::~Service() {
}

::grpc::Status FileSystem::Service::Logs(::grpc::ServerContext* context, const ::palm::monitoring::v1::FileSystemLogsRequest* request, ::palm::monitoring::v1::FileSystemLogsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* Docker_method_names[] = {
  "/palm.monitoring.v1.Docker/Containers",
  "/palm.monitoring.v1.Docker/Statistics",
};

std::unique_ptr< Docker::Stub> Docker::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Docker::Stub> stub(new Docker::Stub(channel, options));
  return stub;
}

Docker::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Containers_(Docker_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Statistics_(Docker_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Docker::Stub::Containers(::grpc::ClientContext* context, const ::palm::monitoring::v1::DockerQueryRequest& request, ::palm::monitoring::v1::DockerContainersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::monitoring::v1::DockerQueryRequest, ::palm::monitoring::v1::DockerContainersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Containers_, context, request, response);
}

void Docker::Stub::async::Containers(::grpc::ClientContext* context, const ::palm::monitoring::v1::DockerQueryRequest* request, ::palm::monitoring::v1::DockerContainersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::monitoring::v1::DockerQueryRequest, ::palm::monitoring::v1::DockerContainersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Containers_, context, request, response, std::move(f));
}

void Docker::Stub::async::Containers(::grpc::ClientContext* context, const ::palm::monitoring::v1::DockerQueryRequest* request, ::palm::monitoring::v1::DockerContainersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Containers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::DockerContainersResponse>* Docker::Stub::PrepareAsyncContainersRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::DockerQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::monitoring::v1::DockerContainersResponse, ::palm::monitoring::v1::DockerQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Containers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::DockerContainersResponse>* Docker::Stub::AsyncContainersRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::DockerQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncContainersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Docker::Stub::Statistics(::grpc::ClientContext* context, const ::palm::monitoring::v1::DockerQueryRequest& request, ::palm::monitoring::v1::DockerStatisticsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::monitoring::v1::DockerQueryRequest, ::palm::monitoring::v1::DockerStatisticsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Statistics_, context, request, response);
}

void Docker::Stub::async::Statistics(::grpc::ClientContext* context, const ::palm::monitoring::v1::DockerQueryRequest* request, ::palm::monitoring::v1::DockerStatisticsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::monitoring::v1::DockerQueryRequest, ::palm::monitoring::v1::DockerStatisticsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Statistics_, context, request, response, std::move(f));
}

void Docker::Stub::async::Statistics(::grpc::ClientContext* context, const ::palm::monitoring::v1::DockerQueryRequest* request, ::palm::monitoring::v1::DockerStatisticsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Statistics_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::DockerStatisticsResponse>* Docker::Stub::PrepareAsyncStatisticsRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::DockerQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::monitoring::v1::DockerStatisticsResponse, ::palm::monitoring::v1::DockerQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Statistics_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::DockerStatisticsResponse>* Docker::Stub::AsyncStatisticsRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::DockerQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStatisticsRaw(context, request, cq);
  result->StartCall();
  return result;
}

Docker::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Docker_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Docker::Service, ::palm::monitoring::v1::DockerQueryRequest, ::palm::monitoring::v1::DockerContainersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Docker::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::monitoring::v1::DockerQueryRequest* req,
             ::palm::monitoring::v1::DockerContainersResponse* resp) {
               return service->Containers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Docker_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Docker::Service, ::palm::monitoring::v1::DockerQueryRequest, ::palm::monitoring::v1::DockerStatisticsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Docker::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::monitoring::v1::DockerQueryRequest* req,
             ::palm::monitoring::v1::DockerStatisticsResponse* resp) {
               return service->Statistics(ctx, req, resp);
             }, this)));
}

Docker::Service::~Service() {
}

::grpc::Status Docker::Service::Containers(::grpc::ServerContext* context, const ::palm::monitoring::v1::DockerQueryRequest* request, ::palm::monitoring::v1::DockerContainersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Docker::Service::Statistics(::grpc::ServerContext* context, const ::palm::monitoring::v1::DockerQueryRequest* request, ::palm::monitoring::v1::DockerStatisticsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* Podman_method_names[] = {
  "/palm.monitoring.v1.Podman/Logs",
  "/palm.monitoring.v1.Podman/Containers",
  "/palm.monitoring.v1.Podman/Statistics",
};

std::unique_ptr< Podman::Stub> Podman::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Podman::Stub> stub(new Podman::Stub(channel, options));
  return stub;
}

Podman::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Logs_(Podman_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Containers_(Podman_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Statistics_(Podman_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Podman::Stub::Logs(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest& request, ::palm::monitoring::v1::PodmanLogsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::monitoring::v1::PodmanQueryRequest, ::palm::monitoring::v1::PodmanLogsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Logs_, context, request, response);
}

void Podman::Stub::async::Logs(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest* request, ::palm::monitoring::v1::PodmanLogsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::monitoring::v1::PodmanQueryRequest, ::palm::monitoring::v1::PodmanLogsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Logs_, context, request, response, std::move(f));
}

void Podman::Stub::async::Logs(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest* request, ::palm::monitoring::v1::PodmanLogsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Logs_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::PodmanLogsResponse>* Podman::Stub::PrepareAsyncLogsRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::monitoring::v1::PodmanLogsResponse, ::palm::monitoring::v1::PodmanQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Logs_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::PodmanLogsResponse>* Podman::Stub::AsyncLogsRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncLogsRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Podman::Stub::Containers(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest& request, ::palm::monitoring::v1::PodmanContainersResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::monitoring::v1::PodmanQueryRequest, ::palm::monitoring::v1::PodmanContainersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Containers_, context, request, response);
}

void Podman::Stub::async::Containers(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest* request, ::palm::monitoring::v1::PodmanContainersResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::monitoring::v1::PodmanQueryRequest, ::palm::monitoring::v1::PodmanContainersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Containers_, context, request, response, std::move(f));
}

void Podman::Stub::async::Containers(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest* request, ::palm::monitoring::v1::PodmanContainersResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Containers_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::PodmanContainersResponse>* Podman::Stub::PrepareAsyncContainersRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::monitoring::v1::PodmanContainersResponse, ::palm::monitoring::v1::PodmanQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Containers_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::PodmanContainersResponse>* Podman::Stub::AsyncContainersRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncContainersRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status Podman::Stub::Statistics(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest& request, ::palm::monitoring::v1::PodmanStatisticsResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::monitoring::v1::PodmanQueryRequest, ::palm::monitoring::v1::PodmanStatisticsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Statistics_, context, request, response);
}

void Podman::Stub::async::Statistics(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest* request, ::palm::monitoring::v1::PodmanStatisticsResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::monitoring::v1::PodmanQueryRequest, ::palm::monitoring::v1::PodmanStatisticsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Statistics_, context, request, response, std::move(f));
}

void Podman::Stub::async::Statistics(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest* request, ::palm::monitoring::v1::PodmanStatisticsResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Statistics_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::PodmanStatisticsResponse>* Podman::Stub::PrepareAsyncStatisticsRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::monitoring::v1::PodmanStatisticsResponse, ::palm::monitoring::v1::PodmanQueryRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Statistics_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::monitoring::v1::PodmanStatisticsResponse>* Podman::Stub::AsyncStatisticsRaw(::grpc::ClientContext* context, const ::palm::monitoring::v1::PodmanQueryRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncStatisticsRaw(context, request, cq);
  result->StartCall();
  return result;
}

Podman::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Podman_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Podman::Service, ::palm::monitoring::v1::PodmanQueryRequest, ::palm::monitoring::v1::PodmanLogsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Podman::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::monitoring::v1::PodmanQueryRequest* req,
             ::palm::monitoring::v1::PodmanLogsResponse* resp) {
               return service->Logs(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Podman_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Podman::Service, ::palm::monitoring::v1::PodmanQueryRequest, ::palm::monitoring::v1::PodmanContainersResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Podman::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::monitoring::v1::PodmanQueryRequest* req,
             ::palm::monitoring::v1::PodmanContainersResponse* resp) {
               return service->Containers(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Podman_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Podman::Service, ::palm::monitoring::v1::PodmanQueryRequest, ::palm::monitoring::v1::PodmanStatisticsResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Podman::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::monitoring::v1::PodmanQueryRequest* req,
             ::palm::monitoring::v1::PodmanStatisticsResponse* resp) {
               return service->Statistics(ctx, req, resp);
             }, this)));
}

Podman::Service::~Service() {
}

::grpc::Status Podman::Service::Logs(::grpc::ServerContext* context, const ::palm::monitoring::v1::PodmanQueryRequest* request, ::palm::monitoring::v1::PodmanLogsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Podman::Service::Containers(::grpc::ServerContext* context, const ::palm::monitoring::v1::PodmanQueryRequest* request, ::palm::monitoring::v1::PodmanContainersResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status Podman::Service::Statistics(::grpc::ServerContext* context, const ::palm::monitoring::v1::PodmanQueryRequest* request, ::palm::monitoring::v1::PodmanStatisticsResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace palm
}  // namespace monitoring
}  // namespace v1

