// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: wechat-pay.proto

#include "wechat-pay.pb.h"
#include "wechat-pay.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
namespace palm {
namespace wechat {
namespace pay {
namespace v1 {

static const char* WeChatPayNative_method_names[] = {
  "/palm.wechat.pay.v1.WeChatPayNative/Prepay",
};

std::unique_ptr< WeChatPayNative::Stub> WeChatPayNative::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WeChatPayNative::Stub> stub(new WeChatPayNative::Stub(channel, options));
  return stub;
}

WeChatPayNative::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Prepay_(WeChatPayNative_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WeChatPayNative::Stub::Prepay(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest& request, ::palm::wechat::pay::v1::WeChatPayNativeQrCodeUrlResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayPrepayRequest, ::palm::wechat::pay::v1::WeChatPayNativeQrCodeUrlResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Prepay_, context, request, response);
}

void WeChatPayNative::Stub::async::Prepay(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest* request, ::palm::wechat::pay::v1::WeChatPayNativeQrCodeUrlResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayPrepayRequest, ::palm::wechat::pay::v1::WeChatPayNativeQrCodeUrlResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Prepay_, context, request, response, std::move(f));
}

void WeChatPayNative::Stub::async::Prepay(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest* request, ::palm::wechat::pay::v1::WeChatPayNativeQrCodeUrlResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Prepay_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayNativeQrCodeUrlResponse>* WeChatPayNative::Stub::PrepareAsyncPrepayRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayNativeQrCodeUrlResponse, ::palm::wechat::pay::v1::WeChatPayPrepayRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Prepay_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayNativeQrCodeUrlResponse>* WeChatPayNative::Stub::AsyncPrepayRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPrepayRaw(context, request, cq);
  result->StartCall();
  return result;
}

WeChatPayNative::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayNative_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayNative::Service, ::palm::wechat::pay::v1::WeChatPayPrepayRequest, ::palm::wechat::pay::v1::WeChatPayNativeQrCodeUrlResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayNative::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayPrepayRequest* req,
             ::palm::wechat::pay::v1::WeChatPayNativeQrCodeUrlResponse* resp) {
               return service->Prepay(ctx, req, resp);
             }, this)));
}

WeChatPayNative::Service::~Service() {
}

::grpc::Status WeChatPayNative::Service::Prepay(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest* request, ::palm::wechat::pay::v1::WeChatPayNativeQrCodeUrlResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* WeChatPayJsapi_method_names[] = {
  "/palm.wechat.pay.v1.WeChatPayJsapi/Prepay",
  "/palm.wechat.pay.v1.WeChatPayJsapi/QueryOrderByOutTradeNo",
  "/palm.wechat.pay.v1.WeChatPayJsapi/QueryOrderById",
  "/palm.wechat.pay.v1.WeChatPayJsapi/CloseOrder",
};

std::unique_ptr< WeChatPayJsapi::Stub> WeChatPayJsapi::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WeChatPayJsapi::Stub> stub(new WeChatPayJsapi::Stub(channel, options));
  return stub;
}

WeChatPayJsapi::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Prepay_(WeChatPayJsapi_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryOrderByOutTradeNo_(WeChatPayJsapi_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryOrderById_(WeChatPayJsapi_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_CloseOrder_(WeChatPayJsapi_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WeChatPayJsapi::Stub::Prepay(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest& request, ::palm::wechat::pay::v1::WeChatPayJsapiPrepayIdResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayPrepayRequest, ::palm::wechat::pay::v1::WeChatPayJsapiPrepayIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Prepay_, context, request, response);
}

void WeChatPayJsapi::Stub::async::Prepay(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest* request, ::palm::wechat::pay::v1::WeChatPayJsapiPrepayIdResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayPrepayRequest, ::palm::wechat::pay::v1::WeChatPayJsapiPrepayIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Prepay_, context, request, response, std::move(f));
}

void WeChatPayJsapi::Stub::async::Prepay(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest* request, ::palm::wechat::pay::v1::WeChatPayJsapiPrepayIdResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Prepay_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayJsapiPrepayIdResponse>* WeChatPayJsapi::Stub::PrepareAsyncPrepayRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayJsapiPrepayIdResponse, ::palm::wechat::pay::v1::WeChatPayPrepayRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Prepay_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayJsapiPrepayIdResponse>* WeChatPayJsapi::Stub::AsyncPrepayRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncPrepayRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WeChatPayJsapi::Stub::QueryOrderByOutTradeNo(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByOutTradeNoRequest& request, ::palm::wechat::pay::v1::WeChatPayTradeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayQueryOrderByOutTradeNoRequest, ::palm::wechat::pay::v1::WeChatPayTradeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryOrderByOutTradeNo_, context, request, response);
}

void WeChatPayJsapi::Stub::async::QueryOrderByOutTradeNo(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByOutTradeNoRequest* request, ::palm::wechat::pay::v1::WeChatPayTradeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayQueryOrderByOutTradeNoRequest, ::palm::wechat::pay::v1::WeChatPayTradeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryOrderByOutTradeNo_, context, request, response, std::move(f));
}

void WeChatPayJsapi::Stub::async::QueryOrderByOutTradeNo(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByOutTradeNoRequest* request, ::palm::wechat::pay::v1::WeChatPayTradeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryOrderByOutTradeNo_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayTradeResponse>* WeChatPayJsapi::Stub::PrepareAsyncQueryOrderByOutTradeNoRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByOutTradeNoRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayTradeResponse, ::palm::wechat::pay::v1::WeChatPayQueryOrderByOutTradeNoRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryOrderByOutTradeNo_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayTradeResponse>* WeChatPayJsapi::Stub::AsyncQueryOrderByOutTradeNoRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByOutTradeNoRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryOrderByOutTradeNoRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WeChatPayJsapi::Stub::QueryOrderById(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByIdRequest& request, ::palm::wechat::pay::v1::WeChatPayTradeResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayQueryOrderByIdRequest, ::palm::wechat::pay::v1::WeChatPayTradeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryOrderById_, context, request, response);
}

void WeChatPayJsapi::Stub::async::QueryOrderById(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByIdRequest* request, ::palm::wechat::pay::v1::WeChatPayTradeResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayQueryOrderByIdRequest, ::palm::wechat::pay::v1::WeChatPayTradeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryOrderById_, context, request, response, std::move(f));
}

void WeChatPayJsapi::Stub::async::QueryOrderById(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByIdRequest* request, ::palm::wechat::pay::v1::WeChatPayTradeResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryOrderById_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayTradeResponse>* WeChatPayJsapi::Stub::PrepareAsyncQueryOrderByIdRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByIdRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayTradeResponse, ::palm::wechat::pay::v1::WeChatPayQueryOrderByIdRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryOrderById_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayTradeResponse>* WeChatPayJsapi::Stub::AsyncQueryOrderByIdRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByIdRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryOrderByIdRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WeChatPayJsapi::Stub::CloseOrder(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayCloseOrderRequest& request, ::google::protobuf::Empty* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayCloseOrderRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CloseOrder_, context, request, response);
}

void WeChatPayJsapi::Stub::async::CloseOrder(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayCloseOrderRequest* request, ::google::protobuf::Empty* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayCloseOrderRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CloseOrder_, context, request, response, std::move(f));
}

void WeChatPayJsapi::Stub::async::CloseOrder(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayCloseOrderRequest* request, ::google::protobuf::Empty* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CloseOrder_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* WeChatPayJsapi::Stub::PrepareAsyncCloseOrderRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayCloseOrderRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::google::protobuf::Empty, ::palm::wechat::pay::v1::WeChatPayCloseOrderRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CloseOrder_, context, request);
}

::grpc::ClientAsyncResponseReader< ::google::protobuf::Empty>* WeChatPayJsapi::Stub::AsyncCloseOrderRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayCloseOrderRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCloseOrderRaw(context, request, cq);
  result->StartCall();
  return result;
}

WeChatPayJsapi::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayJsapi_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayJsapi::Service, ::palm::wechat::pay::v1::WeChatPayPrepayRequest, ::palm::wechat::pay::v1::WeChatPayJsapiPrepayIdResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayJsapi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayPrepayRequest* req,
             ::palm::wechat::pay::v1::WeChatPayJsapiPrepayIdResponse* resp) {
               return service->Prepay(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayJsapi_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayJsapi::Service, ::palm::wechat::pay::v1::WeChatPayQueryOrderByOutTradeNoRequest, ::palm::wechat::pay::v1::WeChatPayTradeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayJsapi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayQueryOrderByOutTradeNoRequest* req,
             ::palm::wechat::pay::v1::WeChatPayTradeResponse* resp) {
               return service->QueryOrderByOutTradeNo(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayJsapi_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayJsapi::Service, ::palm::wechat::pay::v1::WeChatPayQueryOrderByIdRequest, ::palm::wechat::pay::v1::WeChatPayTradeResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayJsapi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayQueryOrderByIdRequest* req,
             ::palm::wechat::pay::v1::WeChatPayTradeResponse* resp) {
               return service->QueryOrderById(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayJsapi_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayJsapi::Service, ::palm::wechat::pay::v1::WeChatPayCloseOrderRequest, ::google::protobuf::Empty, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayJsapi::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayCloseOrderRequest* req,
             ::google::protobuf::Empty* resp) {
               return service->CloseOrder(ctx, req, resp);
             }, this)));
}

WeChatPayJsapi::Service::~Service() {
}

::grpc::Status WeChatPayJsapi::Service::Prepay(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayPrepayRequest* request, ::palm::wechat::pay::v1::WeChatPayJsapiPrepayIdResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WeChatPayJsapi::Service::QueryOrderByOutTradeNo(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByOutTradeNoRequest* request, ::palm::wechat::pay::v1::WeChatPayTradeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WeChatPayJsapi::Service::QueryOrderById(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryOrderByIdRequest* request, ::palm::wechat::pay::v1::WeChatPayTradeResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WeChatPayJsapi::Service::CloseOrder(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayCloseOrderRequest* request, ::google::protobuf::Empty* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* WeChatPayBill_method_names[] = {
  "/palm.wechat.pay.v1.WeChatPayBill/Trade",
  "/palm.wechat.pay.v1.WeChatPayBill/FundFlow",
};

std::unique_ptr< WeChatPayBill::Stub> WeChatPayBill::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WeChatPayBill::Stub> stub(new WeChatPayBill::Stub(channel, options));
  return stub;
}

WeChatPayBill::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Trade_(WeChatPayBill_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_FundFlow_(WeChatPayBill_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WeChatPayBill::Stub::Trade(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTradeBillRequest& request, ::palm::wechat::pay::v1::WeChatPayBillResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayTradeBillRequest, ::palm::wechat::pay::v1::WeChatPayBillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Trade_, context, request, response);
}

void WeChatPayBill::Stub::async::Trade(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTradeBillRequest* request, ::palm::wechat::pay::v1::WeChatPayBillResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayTradeBillRequest, ::palm::wechat::pay::v1::WeChatPayBillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Trade_, context, request, response, std::move(f));
}

void WeChatPayBill::Stub::async::Trade(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTradeBillRequest* request, ::palm::wechat::pay::v1::WeChatPayBillResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Trade_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayBillResponse>* WeChatPayBill::Stub::PrepareAsyncTradeRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTradeBillRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayBillResponse, ::palm::wechat::pay::v1::WeChatPayTradeBillRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Trade_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayBillResponse>* WeChatPayBill::Stub::AsyncTradeRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTradeBillRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncTradeRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WeChatPayBill::Stub::FundFlow(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayFundFlowBillRequest& request, ::palm::wechat::pay::v1::WeChatPayBillResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayFundFlowBillRequest, ::palm::wechat::pay::v1::WeChatPayBillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_FundFlow_, context, request, response);
}

void WeChatPayBill::Stub::async::FundFlow(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayFundFlowBillRequest* request, ::palm::wechat::pay::v1::WeChatPayBillResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayFundFlowBillRequest, ::palm::wechat::pay::v1::WeChatPayBillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FundFlow_, context, request, response, std::move(f));
}

void WeChatPayBill::Stub::async::FundFlow(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayFundFlowBillRequest* request, ::palm::wechat::pay::v1::WeChatPayBillResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_FundFlow_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayBillResponse>* WeChatPayBill::Stub::PrepareAsyncFundFlowRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayFundFlowBillRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayBillResponse, ::palm::wechat::pay::v1::WeChatPayFundFlowBillRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_FundFlow_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayBillResponse>* WeChatPayBill::Stub::AsyncFundFlowRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayFundFlowBillRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncFundFlowRaw(context, request, cq);
  result->StartCall();
  return result;
}

WeChatPayBill::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayBill_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayBill::Service, ::palm::wechat::pay::v1::WeChatPayTradeBillRequest, ::palm::wechat::pay::v1::WeChatPayBillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayBill::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayTradeBillRequest* req,
             ::palm::wechat::pay::v1::WeChatPayBillResponse* resp) {
               return service->Trade(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayBill_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayBill::Service, ::palm::wechat::pay::v1::WeChatPayFundFlowBillRequest, ::palm::wechat::pay::v1::WeChatPayBillResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayBill::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayFundFlowBillRequest* req,
             ::palm::wechat::pay::v1::WeChatPayBillResponse* resp) {
               return service->FundFlow(ctx, req, resp);
             }, this)));
}

WeChatPayBill::Service::~Service() {
}

::grpc::Status WeChatPayBill::Service::Trade(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayTradeBillRequest* request, ::palm::wechat::pay::v1::WeChatPayBillResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WeChatPayBill::Service::FundFlow(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayFundFlowBillRequest* request, ::palm::wechat::pay::v1::WeChatPayBillResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* WeChatPayRefund_method_names[] = {
  "/palm.wechat.pay.v1.WeChatPayRefund/Create",
  "/palm.wechat.pay.v1.WeChatPayRefund/Query",
};

std::unique_ptr< WeChatPayRefund::Stub> WeChatPayRefund::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WeChatPayRefund::Stub> stub(new WeChatPayRefund::Stub(channel, options));
  return stub;
}

WeChatPayRefund::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_Create_(WeChatPayRefund_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_Query_(WeChatPayRefund_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WeChatPayRefund::Stub::Create(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayCreateRefundRequest& request, ::palm::wechat::pay::v1::WeChatPayRefundResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayCreateRefundRequest, ::palm::wechat::pay::v1::WeChatPayRefundResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Create_, context, request, response);
}

void WeChatPayRefund::Stub::async::Create(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayCreateRefundRequest* request, ::palm::wechat::pay::v1::WeChatPayRefundResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayCreateRefundRequest, ::palm::wechat::pay::v1::WeChatPayRefundResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, std::move(f));
}

void WeChatPayRefund::Stub::async::Create(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayCreateRefundRequest* request, ::palm::wechat::pay::v1::WeChatPayRefundResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Create_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayRefundResponse>* WeChatPayRefund::Stub::PrepareAsyncCreateRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayCreateRefundRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayRefundResponse, ::palm::wechat::pay::v1::WeChatPayCreateRefundRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Create_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayRefundResponse>* WeChatPayRefund::Stub::AsyncCreateRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayCreateRefundRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCreateRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WeChatPayRefund::Stub::Query(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryRefundRequest& request, ::palm::wechat::pay::v1::WeChatPayRefundResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayQueryRefundRequest, ::palm::wechat::pay::v1::WeChatPayRefundResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_Query_, context, request, response);
}

void WeChatPayRefund::Stub::async::Query(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryRefundRequest* request, ::palm::wechat::pay::v1::WeChatPayRefundResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayQueryRefundRequest, ::palm::wechat::pay::v1::WeChatPayRefundResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Query_, context, request, response, std::move(f));
}

void WeChatPayRefund::Stub::async::Query(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryRefundRequest* request, ::palm::wechat::pay::v1::WeChatPayRefundResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_Query_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayRefundResponse>* WeChatPayRefund::Stub::PrepareAsyncQueryRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryRefundRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayRefundResponse, ::palm::wechat::pay::v1::WeChatPayQueryRefundRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_Query_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayRefundResponse>* WeChatPayRefund::Stub::AsyncQueryRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryRefundRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryRaw(context, request, cq);
  result->StartCall();
  return result;
}

WeChatPayRefund::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayRefund_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayRefund::Service, ::palm::wechat::pay::v1::WeChatPayCreateRefundRequest, ::palm::wechat::pay::v1::WeChatPayRefundResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayRefund::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayCreateRefundRequest* req,
             ::palm::wechat::pay::v1::WeChatPayRefundResponse* resp) {
               return service->Create(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayRefund_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayRefund::Service, ::palm::wechat::pay::v1::WeChatPayQueryRefundRequest, ::palm::wechat::pay::v1::WeChatPayRefundResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayRefund::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayQueryRefundRequest* req,
             ::palm::wechat::pay::v1::WeChatPayRefundResponse* resp) {
               return service->Query(ctx, req, resp);
             }, this)));
}

WeChatPayRefund::Service::~Service() {
}

::grpc::Status WeChatPayRefund::Service::Create(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayCreateRefundRequest* request, ::palm::wechat::pay::v1::WeChatPayRefundResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WeChatPayRefund::Service::Query(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryRefundRequest* request, ::palm::wechat::pay::v1::WeChatPayRefundResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


static const char* WeChatPayTransfer_method_names[] = {
  "/palm.wechat.pay.v1.WeChatPayTransfer/ExecuteBatch",
  "/palm.wechat.pay.v1.WeChatPayTransfer/QueryBatch",
  "/palm.wechat.pay.v1.WeChatPayTransfer/QueryDetail",
  "/palm.wechat.pay.v1.WeChatPayTransfer/GetBillReceipt",
  "/palm.wechat.pay.v1.WeChatPayTransfer/GetElectronicReceipt",
};

std::unique_ptr< WeChatPayTransfer::Stub> WeChatPayTransfer::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< WeChatPayTransfer::Stub> stub(new WeChatPayTransfer::Stub(channel, options));
  return stub;
}

WeChatPayTransfer::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ExecuteBatch_(WeChatPayTransfer_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryBatch_(WeChatPayTransfer_method_names[1], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_QueryDetail_(WeChatPayTransfer_method_names[2], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetBillReceipt_(WeChatPayTransfer_method_names[3], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  , rpcmethod_GetElectronicReceipt_(WeChatPayTransfer_method_names[4], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status WeChatPayTransfer::Stub::ExecuteBatch(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferRequest& request, ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferRequest, ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ExecuteBatch_, context, request, response);
}

void WeChatPayTransfer::Stub::async::ExecuteBatch(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferRequest* request, ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferRequest, ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteBatch_, context, request, response, std::move(f));
}

void WeChatPayTransfer::Stub::async::ExecuteBatch(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferRequest* request, ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ExecuteBatch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferResponse>* WeChatPayTransfer::Stub::PrepareAsyncExecuteBatchRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferResponse, ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ExecuteBatch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferResponse>* WeChatPayTransfer::Stub::AsyncExecuteBatchRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncExecuteBatchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WeChatPayTransfer::Stub::QueryBatch(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferRequest& request, ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferRequest, ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryBatch_, context, request, response);
}

void WeChatPayTransfer::Stub::async::QueryBatch(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferRequest* request, ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferRequest, ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryBatch_, context, request, response, std::move(f));
}

void WeChatPayTransfer::Stub::async::QueryBatch(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferRequest* request, ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryBatch_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferResponse>* WeChatPayTransfer::Stub::PrepareAsyncQueryBatchRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferResponse, ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryBatch_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferResponse>* WeChatPayTransfer::Stub::AsyncQueryBatchRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryBatchRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WeChatPayTransfer::Stub::QueryDetail(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailRequest& request, ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailRequest, ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_QueryDetail_, context, request, response);
}

void WeChatPayTransfer::Stub::async::QueryDetail(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailRequest* request, ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailRequest, ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryDetail_, context, request, response, std::move(f));
}

void WeChatPayTransfer::Stub::async::QueryDetail(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailRequest* request, ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_QueryDetail_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailResponse>* WeChatPayTransfer::Stub::PrepareAsyncQueryDetailRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailResponse, ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_QueryDetail_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailResponse>* WeChatPayTransfer::Stub::AsyncQueryDetailRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncQueryDetailRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WeChatPayTransfer::Stub::GetBillReceipt(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetBillReceiptRequest& request, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayTransferGetBillReceiptRequest, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetBillReceipt_, context, request, response);
}

void WeChatPayTransfer::Stub::async::GetBillReceipt(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetBillReceiptRequest* request, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayTransferGetBillReceiptRequest, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBillReceipt_, context, request, response, std::move(f));
}

void WeChatPayTransfer::Stub::async::GetBillReceipt(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetBillReceiptRequest* request, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetBillReceipt_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse>* WeChatPayTransfer::Stub::PrepareAsyncGetBillReceiptRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetBillReceiptRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse, ::palm::wechat::pay::v1::WeChatPayTransferGetBillReceiptRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetBillReceipt_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse>* WeChatPayTransfer::Stub::AsyncGetBillReceiptRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetBillReceiptRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetBillReceiptRaw(context, request, cq);
  result->StartCall();
  return result;
}

::grpc::Status WeChatPayTransfer::Stub::GetElectronicReceipt(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetElectronicReceiptRequest& request, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse* response) {
  return ::grpc::internal::BlockingUnaryCall< ::palm::wechat::pay::v1::WeChatPayTransferGetElectronicReceiptRequest, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_GetElectronicReceipt_, context, request, response);
}

void WeChatPayTransfer::Stub::async::GetElectronicReceipt(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetElectronicReceiptRequest* request, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::palm::wechat::pay::v1::WeChatPayTransferGetElectronicReceiptRequest, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetElectronicReceipt_, context, request, response, std::move(f));
}

void WeChatPayTransfer::Stub::async::GetElectronicReceipt(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetElectronicReceiptRequest* request, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_GetElectronicReceipt_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse>* WeChatPayTransfer::Stub::PrepareAsyncGetElectronicReceiptRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetElectronicReceiptRequest& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse, ::palm::wechat::pay::v1::WeChatPayTransferGetElectronicReceiptRequest, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_GetElectronicReceipt_, context, request);
}

::grpc::ClientAsyncResponseReader< ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse>* WeChatPayTransfer::Stub::AsyncGetElectronicReceiptRaw(::grpc::ClientContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetElectronicReceiptRequest& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncGetElectronicReceiptRaw(context, request, cq);
  result->StartCall();
  return result;
}

WeChatPayTransfer::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayTransfer_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayTransfer::Service, ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferRequest, ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayTransfer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferRequest* req,
             ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferResponse* resp) {
               return service->ExecuteBatch(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayTransfer_method_names[1],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayTransfer::Service, ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferRequest, ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayTransfer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferRequest* req,
             ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferResponse* resp) {
               return service->QueryBatch(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayTransfer_method_names[2],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayTransfer::Service, ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailRequest, ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayTransfer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailRequest* req,
             ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailResponse* resp) {
               return service->QueryDetail(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayTransfer_method_names[3],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayTransfer::Service, ::palm::wechat::pay::v1::WeChatPayTransferGetBillReceiptRequest, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayTransfer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayTransferGetBillReceiptRequest* req,
             ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse* resp) {
               return service->GetBillReceipt(ctx, req, resp);
             }, this)));
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      WeChatPayTransfer_method_names[4],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< WeChatPayTransfer::Service, ::palm::wechat::pay::v1::WeChatPayTransferGetElectronicReceiptRequest, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](WeChatPayTransfer::Service* service,
             ::grpc::ServerContext* ctx,
             const ::palm::wechat::pay::v1::WeChatPayTransferGetElectronicReceiptRequest* req,
             ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse* resp) {
               return service->GetElectronicReceipt(ctx, req, resp);
             }, this)));
}

WeChatPayTransfer::Service::~Service() {
}

::grpc::Status WeChatPayTransfer::Service::ExecuteBatch(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferRequest* request, ::palm::wechat::pay::v1::WeChatPayExecuteBatchTransferResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WeChatPayTransfer::Service::QueryBatch(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferRequest* request, ::palm::wechat::pay::v1::WeChatPayQueryBatchTransferResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WeChatPayTransfer::Service::QueryDetail(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailRequest* request, ::palm::wechat::pay::v1::WeChatPayQueryTransferDetailResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WeChatPayTransfer::Service::GetBillReceipt(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetBillReceiptRequest* request, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}

::grpc::Status WeChatPayTransfer::Service::GetElectronicReceipt(::grpc::ServerContext* context, const ::palm::wechat::pay::v1::WeChatPayTransferGetElectronicReceiptRequest* request, ::palm::wechat::pay::v1::WeChatPayTransferGetReceiptResponse* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


}  // namespace palm
}  // namespace wechat
}  // namespace pay
}  // namespace v1

