// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dahlia.proto
// Protobuf Java Version: 4.29.0

package com.github.saturn_xiv.palm.plugins.dahlia.v1;

public interface TeXLiveTaskOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.dahlia.v1.TeXLiveTask)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.palm.dahlia.v1.File output = 1;</code>
   * @return Whether the output field is set.
   */
  boolean hasOutput();
  /**
   * <code>.palm.dahlia.v1.File output = 1;</code>
   * @return The output.
   */
  com.github.saturn_xiv.palm.plugins.dahlia.v1.File getOutput();
  /**
   * <code>.palm.dahlia.v1.File output = 1;</code>
   */
  com.github.saturn_xiv.palm.plugins.dahlia.v1.FileOrBuilder getOutputOrBuilder();

  /**
   * <code>.palm.dahlia.v1.TeXLiveTask.Apa7 apa7 = 11;</code>
   * @return Whether the apa7 field is set.
   */
  boolean hasApa7();
  /**
   * <code>.palm.dahlia.v1.TeXLiveTask.Apa7 apa7 = 11;</code>
   * @return The apa7.
   */
  com.github.saturn_xiv.palm.plugins.dahlia.v1.TeXLiveTask.Apa7 getApa7();
  /**
   * <code>.palm.dahlia.v1.TeXLiveTask.Apa7 apa7 = 11;</code>
   */
  com.github.saturn_xiv.palm.plugins.dahlia.v1.TeXLiveTask.Apa7OrBuilder getApa7OrBuilder();

  /**
   * <code>.palm.dahlia.v1.TeXLiveTask.Mla8 mla8 = 12;</code>
   * @return Whether the mla8 field is set.
   */
  boolean hasMla8();
  /**
   * <code>.palm.dahlia.v1.TeXLiveTask.Mla8 mla8 = 12;</code>
   * @return The mla8.
   */
  com.github.saturn_xiv.palm.plugins.dahlia.v1.TeXLiveTask.Mla8 getMla8();
  /**
   * <code>.palm.dahlia.v1.TeXLiveTask.Mla8 mla8 = 12;</code>
   */
  com.github.saturn_xiv.palm.plugins.dahlia.v1.TeXLiveTask.Mla8OrBuilder getMla8OrBuilder();

  /**
   * <code>.palm.dahlia.v1.TeXLiveTask.Cmos cmos = 13;</code>
   * @return Whether the cmos field is set.
   */
  boolean hasCmos();
  /**
   * <code>.palm.dahlia.v1.TeXLiveTask.Cmos cmos = 13;</code>
   * @return The cmos.
   */
  com.github.saturn_xiv.palm.plugins.dahlia.v1.TeXLiveTask.Cmos getCmos();
  /**
   * <code>.palm.dahlia.v1.TeXLiveTask.Cmos cmos = 13;</code>
   */
  com.github.saturn_xiv.palm.plugins.dahlia.v1.TeXLiveTask.CmosOrBuilder getCmosOrBuilder();

  com.github.saturn_xiv.palm.plugins.dahlia.v1.TeXLiveTask.ContentCase getContentCase();
}
