flyway.user=www
flyway.password=change-me
flyway.url=jdbc:postgresql://127.0.0.1:5432/dahlia_dev
flyway.locations=filesystem:src/main/resources/db/migrations/postgresql
flyway.validateMigrationNaming=true
flyway.cleanDisabled=false