[project]
name = "dahlia"
# version = "2026.9.10"
authors = [{ name = "Jeremy Zheng", email = "jitang.zheng@gmail.com" }]
description = "RBAC services"
readme = "README.md"
requires-python = ">=3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
dependencies = [
    "protobuf~=7.34",
    "grpcio~=1.82",
    "grpcio-reflection",
    "grpcio-health-checking",
    "casbin",
    "sqlalchemy_adapter",
    "casbin-rabbitmq-watcher",
    "psycopg[c,pool]",
    "mysql-connector-python",
]
dynamic = ["version"]

[project.urls]
Homepage = "https://github.com/saturn-xiv/palm/tree/main/dahlia"
Issues = "https://github.com/saturn-xiv/palm/issues"

[project.scripts]
dahlia = "dahlia:main"

[build-system]
requires = ["hatchling >= 1.26", "hatch-vcs"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/dahlia"]

[tool.hatch.version]
source = "vcs"

[tool.hatch.version.raw-options]
root = ".."

[tool.pyright]
include = ["src"]
exclude = ["**/__pycache__", "tmp"]
venvPath = "."
venv = "tmp/python"
pythonVersion = "3.14"
typeCheckingMode = "basic"
