[Unit]
Description=scan lan hosts(loquat).
Wants=network-online.target
After=network-online.target

[Service]
Type=simple
User=root
Group=root
ExecStart=/usr/bin/loquat -c /etc/loquat/config.toml net-scan
WorkingDirectory=/var/lib/loquat
Restart=always

[Install]
WantedBy=multi-user.target
