server {
    listen 80;

    gzip on;
    gzip_min_length 1k;
    gzip_comp_level 9;
    gzip_types text/plain application/javascript application/x-javascript text/css application/xml text/javascript application/x-httpd-php image/jpeg image/gif image/png;
    gzip_vary on;

    root /usr/share/loquat/html;

    location /my {
        alias /usr/share/loquat/dashboard;
        try_files $uri $uri/ /my/index.html;
    }
    location / {
        proxy_pass http://127.0.0.1:8080;

        proxy_set_header    X-Forwarded-Proto $scheme;
        proxy_set_header    X-Forwarded-For $proxy_x_forwarded_for;
        proxy_set_header    Host $http_host;
        proxy_set_header    X-Real-IP $remote_addr;
    }
}
