[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "zinnia"
version = "2025.3.2"
dependencies = [
    "tink",
    "redis[hiredis]",
    "pika",
    "minio",
    "opensearch-dsl",
    "twilio",

    "mariadb",
    "psycopg[binary,pool]",
    "SQLAlchemy",

    "casbin",
    "sqlalchemy_adapter",
    "casbin-rabbitmq-watcher",

    "graphene>=3.1",
    "Flask",
    "gunicorn[gevent]",
]

[project.scripts]
phlox = "zinnia.__main__:main"

[tool.setuptools.packages.find]
where = ["."]
