syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.github.saturn_xiv.palm.plugins.casbin.v1";
option go_package = "./;v2";
package palm.casbin.v1;

import "google/protobuf/empty.proto";

// ----------------------------------------------------------------------------

message Permission {
  Subject subject = 1;
  Object object = 2;
  Action action = 3;
}

// https://casbin.org/docs/rbac#how-to-distinguish-role-from-user
message Subject {
  oneof by {
    User user = 1;
    Role role = 2;
  }
}

message User {
  oneof by {
    uint32 id = 1;
    string code = 2;
  }
}

message Role {
  message Root {}
  message Administrator {}
  message Other {
    string code = 1;
  }
  oneof by {
    Root root = 1;
    Administrator administrator = 2;
    Other other = 9;
  }
}

message Object {
  string type = 1;
  oneof by {
    uint32 id = 11;
    string code = 12;
    google.protobuf.Empty empty = 13;
  }
}

message Action {
  message Read {}
  message Write {}
  message Append {}
  message Execute {}
  message Credit {}
  message Debit {}
  message Inquiry {}
  message Other {
    string code = 1;
  }
  oneof by {
    Read read = 1;
    Write write = 2;
    Append append = 3;
    Execute execute = 4;
    Credit credit = 5;
    Debit debit = 6;
    Inquiry inquiry = 7;
    Other other = 9;
  }
}

message WatcherMessage {
  enum Method {
    Update = 0;
    UpdateForSavePolicy = 1;
    UpdateForAddPolicy = 2;
    UpdateForAddPolicies = 3;
    UpdateForRemovePolicy = 4;
    UpdateForRemoveFilteredPolicy = 5;
    UpdateForRemovePolicies = 6;
    UpdateForUpdatePolicy = 7;
    UpdateForUpdatePolicies = 8;
  }
  string id = 1;
  Method method = 2;
}

// ----------------------------------------------------------------------------

service Policy {
  rpc GetAllUsers(google.protobuf.Empty) returns (UsersResponse) {}
  rpc GetAllObjects(google.protobuf.Empty) returns (ObjectsResponse) {}
  rpc GetAllActions(google.protobuf.Empty) returns (ActionsResponse) {}
  rpc GetAllRoles(google.protobuf.Empty) returns (RolesResponse) {}

  rpc Has(UserRoleRequest) returns (BoolResponse) {}
  rpc Can(UserPermissionRequest) returns (BoolResponse) {}

  rpc GetRolesForUser(User) returns (RolesResponse) {}
  rpc GetImplicitRolesForUser(User) returns (RolesResponse) {}
  rpc GetUsersForRole(Role) returns (UsersResponse) {}
  rpc HasRoleForUser(UserRoleRequest) returns (BoolResponse) {}
  rpc AddRoleForUser(UserRoleRequest) returns (google.protobuf.Empty) {}
  rpc DeleteRoleForUser(UserRoleRequest) returns (google.protobuf.Empty) {}
  rpc DeleteUser(User) returns (google.protobuf.Empty) {}
  rpc DeleteRole(Role) returns (google.protobuf.Empty) {}

  rpc GetPermissionsForUser(User) returns (PermissionsResponse) {}
  rpc GetImplicitPermissionsForUser(User) returns (PermissionsResponse) {}
  rpc AddPermissionForUser(UserPermissionRequest)
      returns (google.protobuf.Empty) {}
  rpc DeletePermissionForUser(UserPermissionRequest)
      returns (google.protobuf.Empty) {}
  rpc HasPermissionForUser(UserPermissionRequest) returns (BoolResponse) {}

  rpc GetPermissionsForRole(Role) returns (PermissionsResponse) {}
  rpc GetImplicitPermissionsForRole(Role) returns (PermissionsResponse) {}
  rpc AddPermissionForRole(RolePermissionRequest)
      returns (google.protobuf.Empty) {}
  rpc DeletePermissionForRole(RolePermissionRequest)
      returns (google.protobuf.Empty) {}
  rpc HasPermissionForRole(RolePermissionRequest) returns (BoolResponse) {}
}

message UserRoleRequest {
  User user = 1;
  Role role = 2;
}
message BoolResponse {
  bool yes = 1;
}
message UserPermissionRequest {
  User user = 1;
  Object object = 2;
  Action action = 3;
}

message RolePermissionRequest {
  Role role = 1;
  Object object = 2;
  Action action = 3;
}

message PermissionsResponse {
  repeated Permission items = 1;
}

message RolesResponse {
  repeated Role items = 1;
}

message UsersResponse {
  repeated User items = 1;
}

message ActionsResponse {
  repeated Action items = 1;
}

message ObjectsResponse {
  repeated Object items = 1;
}
