namespace palm.email.v1;

table Address {
    name: string (required);
    email: string (required);
}

table Body {
    html: bool;
    content: string (required);
}

table Attachment {
    inline_id: string;
    name: string (required);
    body: [ubyte] (required);
    content_type: string (required);
}

table Task {
    from: Address (required);
    to: Address (required);
    reply_to: Address;
    cc: [Address];
    bcc: [Address];
    subject: string (required);
    body: Body (required);
    attachments: [Attachment];
}
