syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.github.saturn_xiv.palm.plugins.monitoring.v1";
option go_package = "./;v2";
package palm.monitoring.v1;

import "google/protobuf/timestamp.proto";

import "portal.proto";

// ----------------------------------------------------------------------------
service Site {
  rpc Layout(SiteLayoutRequest) returns (SiteLayoutResponse) {}
}
message SiteLayoutRequest {
  string lang = 1;
}
message SiteLayoutResponse {
  message CurrentUser {
    string name = 1;
  }
  optional CurrentUser user = 1;
  string locale = 8;
  repeated string available_languages = 9;
  string git_version = 11;
  string build_time = 12;
  google.protobuf.Timestamp created_at = 99;
}
// ----------------------------------------------------------------------------

message Heartbeat {
  message Http {
    string url = 1;
  }
  message MySql {}
  message PostgreSql {}
  message RabbitMQ {}
  message Redis {
    string host = 1;
    int32 port = 2;
    bool cluster = 3;
  }
  message Minio {}

  oneof by {
    Http http = 1;
    MySql mysql = 2;
    PostgreSql postgresql = 3;
    RabbitMQ rabbitmq = 4;
    Redis redis = 5;
    Minio minio = 6;
  }
}

// ----------------------------------------------------------------------------
service Systemd {
  rpc Journal(SystemdJournalRequest) returns (SystemdJournalResponse) {}
}
message SystemdJournalRequest {
  message All {}
  oneof by {
    All all = 1;
    string host = 2;
    string name = 3;
  }
  palm.portal.v1.Page page = 99;
}
message SystemdJournalResponse {
  message Item {
    string host = 1;
    string name = 2;
    string message = 3;
    google.protobuf.Timestamp created_at = 9;
  }
  repeated Item items = 1;
  palm.portal.v1.Pagination pagination = 9;
}
// ----------------------------------------------------------------------------

service FileSystem {
  rpc Logs(FileSystemLogsRequest) returns (FileSystemLogsResponse) {}
}
message FileSystemLogsRequest {
  message All {}
  oneof by {
    All all = 1;
    string host = 2;
    string file = 3;
  }
  palm.portal.v1.Page page = 99;
}
message FileSystemLogsResponse {
  message Item {
    string host = 1;
    string file = 2;
    string line = 3;
    google.protobuf.Timestamp created_at = 9;
  }
  repeated Item items = 1;
  palm.portal.v1.Pagination pagination = 9;
}
// ----------------------------------------------------------------------------

service Docker {
  rpc Containers(PodmanQueryRequest) returns (DockerContainersResponse) {}
  rpc Statistics(PodmanQueryRequest) returns (DockerStatisticsResponse) {}
  rpc Logs(PodmanQueryRequest) returns (PodmanLogsResponse) {}
}

message DockerContainersResponse {
  message Item {
    string command = 1;
    google.protobuf.Timestamp created_at = 2;
    string id = 3;
    string image = 4;
    string labels = 5;
    string local_volumes = 6;
    string mounts = 7;
    string names = 8;
    string networks = 9;
    optional string platform = 10;
    string ports = 11;
    string running_for = 12;
    string size = 13;
    string state = 14;
    string status = 15;

    string host = 98;
    google.protobuf.Timestamp updated_at = 99;
  }
  repeated Item items = 1;
  palm.portal.v1.Pagination pagination = 9;
}
message DockerStatisticsResponse {
  message Item {
    string block_io = 1;
    string cpu_percent = 2;
    string container = 3;
    string id = 4;
    string mem_percent = 5;
    string mem_usage = 6;
    string name = 7;
    string net_io = 8;
    string pids = 9;

    string host = 98;
    google.protobuf.Timestamp created_at = 99;
  }
  repeated Item items = 1;
  palm.portal.v1.Pagination pagination = 9;
}
// ----------------------------------------------------------------------------

service Podman {
  rpc Logs(PodmanQueryRequest) returns (PodmanLogsResponse) {}
  rpc Containers(PodmanQueryRequest) returns (PodmanContainersResponse) {}
  rpc Statistics(PodmanQueryRequest) returns (PodmanStatisticsResponse) {}
}

message PodmanQueryRequest {
  message All {}
  oneof by {
    All all = 1;
    string host = 2;
    string id = 3;
    string name = 4;
  }
  google.protobuf.Timestamp from = 91;
  google.protobuf.Timestamp to = 92;
  palm.portal.v1.Page page = 99;
}

message PodmanLogsResponse {
  message Item {
    string host = 1;
    string id = 2;
    string full_id = 3;
    string name = 4;
    string message = 5;
    google.protobuf.Timestamp created_at = 9;
  }
  repeated Item items = 1;
  palm.portal.v1.Pagination pagination = 9;
}
message PodmanContainersResponse {
  message Item {
    string id = 1;
    string image = 2;
    string image_id = 3;
    map<string, string> labels = 4;
    repeated string mounts = 5;
    repeated string names = 6;
    repeated string command = 7;
    int32 pid = 11;
    string state = 12;
    int64 started_at = 13;
    string created_at = 14;
    int64 created = 15;
    string status = 16;
    bool exited = 21;
    int64 exited_at = 22;
    int32 exit_code = 23;

    string host = 98;
    google.protobuf.Timestamp updated_at = 99;
  }
  repeated Item items = 1;
  palm.portal.v1.Pagination pagination = 9;
}
message PodmanStatisticsResponse {
  message Item {
    string id = 1;
    string name = 2;
    string cpu_time = 3;
    string cpu_percent = 4;
    string avg_cpu = 5;
    string mem_usage = 6;
    string mem_percent = 7;
    string net_io = 8;
    string block_io = 9;
    string pids = 10;
    string host = 98;
    google.protobuf.Timestamp created_at = 99;
  }
  repeated Item items = 1;
  palm.portal.v1.Pagination pagination = 9;
}

// ----------------------------------------------------------------------------
