syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.github.saturn_xiv.palm.plugins.portal.v1";
option go_package = "./;v2";
package palm.portal.v1;

// import "google/protobuf/empty.proto";
import "google/protobuf/duration.proto";
// import "google/protobuf/timestamp.proto";

service User {
  rpc SignInByEmail(UserSignInByEmailRequest) returns (UserSignInResponse) {}
}
message UserSignInByEmailRequest {
  string email = 1;
  string password = 2;
  optional google.protobuf.Duration ttl = 9;
}
message UserSignInResponse {
  string token = 1;
}

service Policy {}

service Site {}
