syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.github.saturn_xiv.palm.plugins.portal.v1";
option go_package = "./;v2";
package palm.portal.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

// ----------------------------------------------------------------------------
message Page {
  uint32 index = 1;
  uint32 size = 2;
}
message Pagination {
  uint32 total = 1;
  uint32 index = 2;
  uint32 size = 3;
}
message IdRequest {
  uint32 id = 1;
}

// ----------------------------------------------------------------------------
service Locale {
  rpc Index(Page) returns (LocaleIndexResponse) {}
  rpc Create(LocaleCreateRequest) returns (google.protobuf.Empty) {}
  rpc Update(LocaleUpdateRequest) returns (google.protobuf.Empty) {}
  rpc Destroy(IdRequest) returns (google.protobuf.Empty) {}
  rpc ByLang(LocaleByLangRequest) returns (LocaleByLangResponse) {}
}
message LocaleByLangRequest {
  string lang = 1;
}
message LocaleByLangResponse {
  message Item {
    string code = 1;
    string message = 2;
  }
  repeated Item items = 1;
}
message LocaleUpdateRequest {
  uint32 id = 1;
  string message = 2;
}
message LocaleCreateRequest {
  string lang = 1;
  string code = 2;
  string message = 3;
}
message LocaleIndexResponse {
  message Item {
    uint32 id = 1;
    string lang = 2;
    string code = 3;
    string message = 4;
    google.protobuf.Timestamp updated_at = 9;
  }
  repeated Item items = 1;
  Pagination pagination = 9;
}
message Resource {
  string type = 1;
  optional uint32 id = 2;
}
// ----------------------------------------------------------------------------

service User {
  rpc SignInByEmail(UserSignInByEmailRequest) returns (UserSignInResponse) {}
  rpc IndexLog(Page) returns (UserIndexLogResponse) {}
}
message UserIndexLogResponse {
  message Item {
    enum Level {
      DEBUG = 0;
      INFO = 1;
      WARNING = 2;
      ERROR = 3;
    }
    uint32 id = 1;
    string plugin = 2;
    string ip = 3;
    Level level = 4;
    Resource resource = 5;
    string message = 6;
    google.protobuf.Timestamp created_at = 9;
  }
  repeated Item items = 1;
  Pagination pagination = 9;
}
message UserSignInByEmailRequest {
  string email = 1;
  string password = 2;
  optional google.protobuf.Duration ttl = 9;
}
message UserSignInResponse {
  string token = 1;
}

// ----------------------------------------------------------------------------
service Policy {}

// ----------------------------------------------------------------------------
service Site {
  rpc Timezones(google.protobuf.Empty) returns (SiteTimezonesResponse) {}
  rpc Currencies(google.protobuf.Empty) returns (SiteCurrenciesResponse) {}
  rpc Languages(google.protobuf.Empty) returns (SiteLanguagesResponse) {}
}
message SiteTimezonesResponse {
  repeated string items = 1;
}
message SiteLanguagesResponse {
  repeated string items = 1;
}
message SiteCurrenciesResponse {
  message Item {
    uint32 id = 1;
    string name = 2;
    string code = 3;
    string country = 4;
    optional uint32 units = 5;
    optional bool fund = 6;
  }
  repeated Item items = 1;
}

// ----------------------------------------------------------------------------
