syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.github.saturn_xiv.palm.plugins.router.v1";
option go_package = "./;v2";
package palm.router.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

message Firewall {
  enum Protocol {
    Tcp = 0;
    Udp = 1;
  }
  message Input {
    Protocol protocol = 1;
    uint32 port = 2;
  }
  message Nat {
    message Destination {
      string ip = 1;
      uint32 port = 2;
    }
    Protocol protocol = 1;
    uint32 port = 2;
    Destination destination = 3;
  }
  repeated Input input = 1;
  repeated Nat nat = 2;
  bool ping = 9;
}

message Wan {
  message Nat {}
  string name = 1;
  string address = 11;
  string netmask = 12;
  string gateway = 13;
  uint32 cidr = 19;
  repeated string dns = 14;
  Firewall firewall = 15;
  uint32 weight = 98;
  string description = 99;
}
message Lan {
  message Dhcp {
    message Host {
      string name = 1;
      string mac = 2;
    }
    string begin = 1;
    string end = 2;
    repeated string dns = 3;
    map<string, Host> reserved_hosts = 9;
  }
  string name = 1;
  bool blacklist_mode = 9;
  string address = 11;
  string netmask = 12;
  uint32 cidr = 13;
  string network = 14;
  optional Dhcp dhcp = 19;
  string description = 99;
}

message Network {
  message Item {
    oneof interface {
      Wan wan = 1;
      Lan lan = 2;
    }
  }
  map<string, Item> items = 1;
}

message Host {
  string mac = 1;
  string ip = 2;
  string name = 3;
  google.protobuf.Timestamp last_found = 9;
}

// ----------------------------------------------------------------------------
service Administrator {
  rpc SignIn(AdministratorSignInRequest) returns (AdministratorSignInResponse) {
  }
  rpc SignOut(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc SetPassword(AdministratorSetPasswordRequest)
      returns (google.protobuf.Empty) {}
}

message AdministratorSignInRequest {
  string name = 1;
  string password = 2;
  google.protobuf.Duration ttl = 9;
}

message AdministratorSignInResponse {
  string token = 1;
  string name = 2;
  string locale = 11;
  string timezone = 12;
  repeated string languages = 19;
}

message AdministratorSetPasswordRequest {
  string current_password = 1;
  string new_password = 2;
}

// ----------------------------------------------------------------------------

service Router {
  rpc SetEthernet(RouterIndexEthernetResponse.Item)
      returns (google.protobuf.Empty) {}
  rpc IndexEthernet(google.protobuf.Empty)
      returns (RouterIndexEthernetResponse) {}
  rpc Reboot(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc Apply(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc FactoryReset(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

message RouterIndexEthernetResponse {
  message Item {
    message Wan {
      string address = 1;
      string netmask = 2;
      string gateway = 3;
      repeated string dns = 4;
    }
    message Lan {
      string network = 1;
    }
    string device = 1;
    string name = 2;
    oneof ethernet {
      Wan wan = 11;
      Lan lan = 12;
      google.protobuf.Empty empty = 19;
    }
    string description = 98;
    bool enable = 99;
  }
  repeated Item items = 1;
}

// ----------------------------------------------------------------------------

service User {
  rpc Index(google.protobuf.Empty) returns (UserIndexResponse) {}
  rpc Create(UserCreateRequest) returns (google.protobuf.Empty) {}
  rpc SetRealName(UserSetRealNameRequest) returns (google.protobuf.Empty) {}
  rpc SetContact(UserSetContactRequest) returns (google.protobuf.Empty) {}
  rpc SetWifi(UserSetWifiRequest) returns (google.protobuf.Empty) {}
}
message UserSetRealNameRequest {
  uint32 id = 1;
  string real_name = 2;
}
message UserSetWifiRequest {
  uint32 id = 1;
  UserIndexResponse.Item.Wifi wifi = 2;
}
message UserSetDetailsRequest {
  uint32 id = 1;
  string real_name = 2;
  UserIndexResponse.Item.Wifi wifi = 3;
}
message UserSetContactRequest {
  uint32 id = 1;
  UserIndexResponse.Item.Contact contact = 2;
}
message UserCreateRequest {
  string real_name = 1;
  UserIndexResponse.Item.Wifi wifi = 2;
}
message UserIndexResponse {
  message Item {
    message Wifi {
      string nickname = 1;
      string password = 2;
      google.protobuf.Timestamp begin_at = 3;
      google.protobuf.Timestamp end_at = 4;
    }
    message Contact {
      optional string wechat = 1;
      optional string address = 2;
      optional string phone = 3;
      optional string email = 4;
    }
    uint32 id = 1;
    string real_name = 2;
    Wifi wifi = 3;
    Contact contact = 9;
  }
  repeated Item items = 1;
}
