syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.github.saturn_xiv.palm.plugins.router.v1";
option go_package = "./;v2";
package palm.router.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

import "portal.proto";

// message Firewall {
//   enum Protocol {
//     Tcp = 0;
//     Udp = 1;
//   }
//   message Input {
//     Protocol protocol = 1;
//     uint32 port = 2;
//   }
//   enum Weekday {
//     Sun = 0;
//     Mon = 1;
//     Tue = 2;
//     Wed = 3;
//     Thu = 4;
//     Fri = 5;
//     Sat = 6;
//   }

//   message TimeRange {
//     message Item {
//       uint32 hour = 1;
//       uint32 minute = 2;
//     }
//     Item begin = 1;
//     Item end = 2;
//   }
//   message Nat {
//     message Destination {
//       string ip = 1;
//       uint32 port = 2;
//     }
//     Protocol protocol = 1;
//     uint32 port = 2;
//     Destination destination = 3;
//   }
//   message Output {
//     repeated Weekday weekdays = 1;
//     optional TimeRange time_range = 2;
//     oneof limit {
//       string host = 11;
//       // iftop KB
//       uint32 speed = 12;
//     }
//     string mac = 99;
//   }
//   repeated Input input = 1;
//   repeated Nat nat = 2;
//   bool ping = 9;
// }

message Wan {
  message Nat {}

  message Static {
    string address = 11;
    string netmask = 12;
    string gateway = 13;
    uint32 cidr = 19;
    repeated string dns = 14;
  }

  string name = 1;
  oneof ip {
    Static static = 2;
    google.protobuf.Empty dhcp = 3;
  }
  uint32 weight = 98;
  string description = 99;
}
message Lan {
  message Dhcp {
    message Host {
      // -.a-zA-Z0-9
      string name = 1;
      string mac = 2;
    }
    string begin = 1;
    string end = 2;
    repeated string dns = 3;
    map<string, Host> reserved_hosts = 9;
  }
  string name = 1;
  bool blacklist_mode = 9;
  string address = 11;
  string netmask = 12;
  uint32 cidr = 13;
  string network = 14;
  optional Dhcp dhcp = 19;
  string description = 99;
}

message Network {
  message Item {
    oneof interface {
      Wan wan = 1;
      Lan lan = 2;
    }
  }
  map<string, Item> items = 1;
}

// message Host {
//   string mac = 1;
//   string ip = 2;
//   string name = 3;
//   google.protobuf.Timestamp last_found = 9;
// }

// ----------------------------------------------------------------------------

service Administrator {
  rpc SignIn(AdministratorSignInRequest) returns (AdministratorSignInResponse) {
  }
  rpc SignOut(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc Update(AdministratorUpdateRequest) returns (google.protobuf.Empty) {}
}

message AdministratorSignInRequest {
  AdministratorUpdateRequest.Item user = 1;
  google.protobuf.Duration ttl = 9;
}

message AdministratorSignInResponse {
  string token = 1;
  string locale = 11;
  string timezone = 12;
  repeated string languages = 19;
}

message AdministratorUpdateRequest {
  message Item {
    string name = 1;
    string password = 2;
  }
  Item current = 1;
  Item new = 2;
}

// ----------------------------------------------------------------------------
// service Rule {
//   rpc Index(google.protobuf.Empty) returns (RuleIndexResponse) {}
//   rpc Create(RuleCreateRequest) returns (google.protobuf.Empty) {}
//   rpc Update(RuleUpdateRequest) returns (google.protobuf.Empty) {}
//   rpc Delete(palm.portal.v1.ByIdRequest) returns (google.protobuf.Empty) {}
// }
// message RuleCreateRequest {
//   string device = 1;
//   RuleIndexResponse.Item item = 2;
// }
// message RuleUpdateRequest {
//   uint32 id = 1;
// }
// message RuleIndexResponse {
//   message Item {
//     uint32 id = 1;
//     string device = 2;
//     message Nat {}
//   }
//   repeated Item items = 1;
// }
// ----------------------------------------------------------------------------

service Router {
  rpc SetEthernet(RouterIndexEthernetResponse.Item)
      returns (google.protobuf.Empty) {}
  rpc IndexEthernet(google.protobuf.Empty)
      returns (RouterIndexEthernetResponse) {}
  rpc Reboot(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc Apply(google.protobuf.Empty) returns (google.protobuf.Empty) {}
  rpc FactoryReset(google.protobuf.Empty) returns (google.protobuf.Empty) {}
}

enum Region {
  Global = 0;
  China = 1;
}

message RouterIndexEthernetResponse {
  message Item {
    message Wan {
      message Static {
        string address = 1;
        string netmask = 2;
        string gateway = 3;
        repeated string dns = 9;
      }
      oneof ip {
        Static static = 1;
        google.protobuf.Empty dhcp = 2;
      }
    }
    message Lan {
      string address = 1;
      string netmask = 2;
      Region region = 9;
    }
    string device = 1;
    string mac = 2;
    string name = 3;
    oneof ethernet {
      Wan wan = 11;
      Lan lan = 12;
      google.protobuf.Empty empty = 19;
    }
    string description = 98;
    bool enable = 99;
  }
  repeated Item items = 1;
}

// ----------------------------------------------------------------------------

service User {
  rpc Index(google.protobuf.Empty) returns (UserIndexResponse) {}
  rpc Create(UserCreateRequest) returns (google.protobuf.Empty) {}
  rpc SetRealName(UserSetRealNameRequest) returns (google.protobuf.Empty) {}
  rpc SetContact(UserSetContactRequest) returns (google.protobuf.Empty) {}
  rpc SetWifi(UserSetWifiRequest) returns (google.protobuf.Empty) {}
}
message UserSetRealNameRequest {
  uint32 id = 1;
  string real_name = 2;
}
message UserSetWifiRequest {
  uint32 id = 1;
  UserIndexResponse.Item.Wifi wifi = 2;
}
message UserSetDetailsRequest {
  uint32 id = 1;
  string real_name = 2;
  UserIndexResponse.Item.Wifi wifi = 3;
}
message UserSetContactRequest {
  uint32 id = 1;
  UserIndexResponse.Item.Contact contact = 2;
}
message UserCreateRequest {
  string real_name = 1;
  UserIndexResponse.Item.Wifi wifi = 2;
}
message UserIndexResponse {
  message Item {
    message Wifi {
      string nickname = 1;
      string password = 2;
      google.protobuf.Timestamp begin_at = 3;
      google.protobuf.Timestamp end_at = 4;
    }
    message Contact {
      optional string wechat = 1;
      optional string address = 2;
      optional string phone = 3;
      optional string email = 4;
    }
    uint32 id = 1;
    string real_name = 2;
    Wifi wifi = 3;
    Contact contact = 9;
  }
  repeated Item items = 1;
}

// ----------------------------------------------------------------------------

service Host {
  rpc Index(google.protobuf.Empty) returns (HostIndexResponse) {}
  rpc SetDescription(HostSetDescriptionRequest)
      returns (google.protobuf.Empty) {}
  rpc Enable(palm.portal.v1.ByIdRequest) returns (google.protobuf.Empty) {}
  rpc Disable(palm.portal.v1.ByIdRequest) returns (google.protobuf.Empty) {}
  rpc Block(HostBlockRequest) returns (google.protobuf.Empty) {}
  rpc SetStaticIpAddress(HostSetStaticIpAddressRequest)
      returns (google.protobuf.Empty) {}
  rpc SetDhcpAddress(HostSetDhcpAddressRequest)
      returns (google.protobuf.Empty) {}
}
message HostIndexResponse {
  message Item {
    uint32 id = 1;
    string name = 2;
    string ip = 3;
    string mac = 4;
    string vendor = 5;
    bool fixed = 6;
    string description = 7;
    optional google.protobuf.Timestamp deleted_at = 8;
    google.protobuf.Timestamp updated_at = 9;
  }
  repeated Item items = 1;
}
message HostSetDescriptionRequest {
  uint32 id = 1;
  string description = 2;
}
message HostBlockRequest {
  enum Weekday {
    Sun = 0;
    Mon = 1;
    Tue = 2;
    Wed = 3;
    Thu = 4;
    Fri = 5;
    Sat = 6;
  }
  message Time {
    uint32 hour = 1;
    uint32 minute = 2;
  }

  uint32 id = 1;
  Time begin = 7;
  Time end = 8;
  repeated Weekday days = 9;
}
message HostSetStaticIpAddressRequest {
  uint32 id = 1;
  string ip = 2;
}
message HostSetDhcpAddressRequest {
  uint32 id = 1;
}
