- name: Install dependencies packages
  become: true
  ansible.builtin.apt:
    pkg:
      - snmpd

- name: Backup /etc/snmp/snmpd.conf
  become: true
  ansible.builtin.copy:
    src: /etc/snmp/snmpd.conf
    dest: "{{ ansible_facts.user_dir }}/backups/etc_snmp_snmpd_conf"
    remote_src: true
    backup: true
    mode: "0444"

- name: Enable snmpd agent
  become: true
  ansible.builtin.lineinfile:
    path: /etc/snmp/snmpd.conf
    regexp: "^agentAddress "
    line: "agentAddress udp:161"

- name: Enable snmpd view
  become: true
  ansible.builtin.lineinfile:
    path: /etc/snmp/snmpd.conf
    line: "view systemonly included .1.3.6.1.4.1.2021"

- name: Enable snmpd service
  become: true
  ansible.builtin.systemd:
    name: snmpd
    enabled: true
    masked: false
