// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.2
// source: lily.proto

package v2

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	TeXLive_ToPdf_FullMethodName = "/palm.lily.v1.TeXLive/ToPdf"
)

// TeXLiveClient is the client API for TeXLive service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type TeXLiveClient interface {
	ToPdf(ctx context.Context, in *TeXLiveRequest, opts ...grpc.CallOption) (*TeXLiveResponse, error)
}

type teXLiveClient struct {
	cc grpc.ClientConnInterface
}

func NewTeXLiveClient(cc grpc.ClientConnInterface) TeXLiveClient {
	return &teXLiveClient{cc}
}

func (c *teXLiveClient) ToPdf(ctx context.Context, in *TeXLiveRequest, opts ...grpc.CallOption) (*TeXLiveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TeXLiveResponse)
	err := c.cc.Invoke(ctx, TeXLive_ToPdf_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TeXLiveServer is the server API for TeXLive service.
// All implementations must embed UnimplementedTeXLiveServer
// for forward compatibility.
type TeXLiveServer interface {
	ToPdf(context.Context, *TeXLiveRequest) (*TeXLiveResponse, error)
	mustEmbedUnimplementedTeXLiveServer()
}

// UnimplementedTeXLiveServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedTeXLiveServer struct{}

func (UnimplementedTeXLiveServer) ToPdf(context.Context, *TeXLiveRequest) (*TeXLiveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ToPdf not implemented")
}
func (UnimplementedTeXLiveServer) mustEmbedUnimplementedTeXLiveServer() {}
func (UnimplementedTeXLiveServer) testEmbeddedByValue()                 {}

// UnsafeTeXLiveServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to TeXLiveServer will
// result in compilation errors.
type UnsafeTeXLiveServer interface {
	mustEmbedUnimplementedTeXLiveServer()
}

func RegisterTeXLiveServer(s grpc.ServiceRegistrar, srv TeXLiveServer) {
	// If the following call pancis, it indicates UnimplementedTeXLiveServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&TeXLive_ServiceDesc, srv)
}

func _TeXLive_ToPdf_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TeXLiveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TeXLiveServer).ToPdf(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: TeXLive_ToPdf_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TeXLiveServer).ToPdf(ctx, req.(*TeXLiveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// TeXLive_ServiceDesc is the grpc.ServiceDesc for TeXLive service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var TeXLive_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "palm.lily.v1.TeXLive",
	HandlerType: (*TeXLiveServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ToPdf",
			Handler:    _TeXLive_ToPdf_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "lily.proto",
}
