// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: email.proto
// Protobuf C++ Version: 5.29.5

#ifndef email_2eproto_2epb_2eh
#define email_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>
#include <utility>

#include "google/protobuf/runtime_version.h"
#if PROTOBUF_VERSION != 5029005
#error "Protobuf C++ gencode is built with an incompatible version of"
#error "Protobuf C++ headers/runtime. See"
#error "https://protobuf.dev/support/cross-version-runtime-guarantee/#cpp"
#endif
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/message_lite.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_email_2eproto

namespace google {
namespace protobuf {
namespace internal {
template <typename T>
::absl::string_view GetAnyMessageName();
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_email_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_email_2eproto;
namespace palm {
namespace email {
namespace v1 {
class Task;
struct TaskDefaultTypeInternal;
extern TaskDefaultTypeInternal _Task_default_instance_;
class Task_Address;
struct Task_AddressDefaultTypeInternal;
extern Task_AddressDefaultTypeInternal _Task_Address_default_instance_;
class Task_Attachment;
struct Task_AttachmentDefaultTypeInternal;
extern Task_AttachmentDefaultTypeInternal _Task_Attachment_default_instance_;
class Task_Body;
struct Task_BodyDefaultTypeInternal;
extern Task_BodyDefaultTypeInternal _Task_Body_default_instance_;
}  // namespace v1
}  // namespace email
}  // namespace palm
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace palm {
namespace email {
namespace v1 {

// ===================================================================


// -------------------------------------------------------------------

class Task_Body final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:palm.email.v1.Task.Body) */ {
 public:
  inline Task_Body() : Task_Body(nullptr) {}
  ~Task_Body() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Task_Body* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Task_Body));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Task_Body(
      ::google::protobuf::internal::ConstantInitialized);

  inline Task_Body(const Task_Body& from) : Task_Body(nullptr, from) {}
  inline Task_Body(Task_Body&& from) noexcept
      : Task_Body(nullptr, std::move(from)) {}
  inline Task_Body& operator=(const Task_Body& from) {
    CopyFrom(from);
    return *this;
  }
  inline Task_Body& operator=(Task_Body&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Task_Body& default_instance() {
    return *internal_default_instance();
  }
  static inline const Task_Body* internal_default_instance() {
    return reinterpret_cast<const Task_Body*>(
        &_Task_Body_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 1;
  friend void swap(Task_Body& a, Task_Body& b) { a.Swap(&b); }
  inline void Swap(Task_Body* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Task_Body* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Task_Body* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Task_Body>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Task_Body& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Task_Body& from) { Task_Body::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Task_Body* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "palm.email.v1.Task.Body"; }

 protected:
  explicit Task_Body(::google::protobuf::Arena* arena);
  Task_Body(::google::protobuf::Arena* arena, const Task_Body& from);
  Task_Body(::google::protobuf::Arena* arena, Task_Body&& from) noexcept
      : Task_Body(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kContentFieldNumber = 1,
    kHtmlFieldNumber = 2,
  };
  // string content = 1;
  void clear_content() ;
  const std::string& content() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_content(Arg_&& arg, Args_... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* value);

  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(
      const std::string& value);
  std::string* _internal_mutable_content();

  public:
  // bool html = 2;
  void clear_html() ;
  bool html() const;
  void set_html(bool value);

  private:
  bool _internal_html() const;
  void _internal_set_html(bool value);

  public:
  // @@protoc_insertion_point(class_scope:palm.email.v1.Task.Body)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      39, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Task_Body& from_msg);
    ::google::protobuf::internal::ArenaStringPtr content_;
    bool html_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_email_2eproto;
};
// -------------------------------------------------------------------

class Task_Attachment final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:palm.email.v1.Task.Attachment) */ {
 public:
  inline Task_Attachment() : Task_Attachment(nullptr) {}
  ~Task_Attachment() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Task_Attachment* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Task_Attachment));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Task_Attachment(
      ::google::protobuf::internal::ConstantInitialized);

  inline Task_Attachment(const Task_Attachment& from) : Task_Attachment(nullptr, from) {}
  inline Task_Attachment(Task_Attachment&& from) noexcept
      : Task_Attachment(nullptr, std::move(from)) {}
  inline Task_Attachment& operator=(const Task_Attachment& from) {
    CopyFrom(from);
    return *this;
  }
  inline Task_Attachment& operator=(Task_Attachment&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Task_Attachment& default_instance() {
    return *internal_default_instance();
  }
  static inline const Task_Attachment* internal_default_instance() {
    return reinterpret_cast<const Task_Attachment*>(
        &_Task_Attachment_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 2;
  friend void swap(Task_Attachment& a, Task_Attachment& b) { a.Swap(&b); }
  inline void Swap(Task_Attachment* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Task_Attachment* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Task_Attachment* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Task_Attachment>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Task_Attachment& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Task_Attachment& from) { Task_Attachment::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Task_Attachment* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "palm.email.v1.Task.Attachment"; }

 protected:
  explicit Task_Attachment(::google::protobuf::Arena* arena);
  Task_Attachment(::google::protobuf::Arena* arena, const Task_Attachment& from);
  Task_Attachment(::google::protobuf::Arena* arena, Task_Attachment&& from) noexcept
      : Task_Attachment(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kContentFieldNumber = 2,
    kInlineFieldNumber = 3,
  };
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // bytes content = 2;
  void clear_content() ;
  const std::string& content() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_content(Arg_&& arg, Args_... args);
  std::string* mutable_content();
  PROTOBUF_NODISCARD std::string* release_content();
  void set_allocated_content(std::string* value);

  private:
  const std::string& _internal_content() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_content(
      const std::string& value);
  std::string* _internal_mutable_content();

  public:
  // bool inline = 3;
  void clear_inline_() ;
  bool inline_() const;
  void set_inline_(bool value);

  private:
  bool _internal_inline_() const;
  void _internal_set_inline_(bool value);

  public:
  // @@protoc_insertion_point(class_scope:palm.email.v1.Task.Attachment)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      2, 3, 0,
      42, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Task_Attachment& from_msg);
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr content_;
    bool inline__;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_email_2eproto;
};
// -------------------------------------------------------------------

class Task_Address final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:palm.email.v1.Task.Address) */ {
 public:
  inline Task_Address() : Task_Address(nullptr) {}
  ~Task_Address() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Task_Address* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Task_Address));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Task_Address(
      ::google::protobuf::internal::ConstantInitialized);

  inline Task_Address(const Task_Address& from) : Task_Address(nullptr, from) {}
  inline Task_Address(Task_Address&& from) noexcept
      : Task_Address(nullptr, std::move(from)) {}
  inline Task_Address& operator=(const Task_Address& from) {
    CopyFrom(from);
    return *this;
  }
  inline Task_Address& operator=(Task_Address&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Task_Address& default_instance() {
    return *internal_default_instance();
  }
  static inline const Task_Address* internal_default_instance() {
    return reinterpret_cast<const Task_Address*>(
        &_Task_Address_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 0;
  friend void swap(Task_Address& a, Task_Address& b) { a.Swap(&b); }
  inline void Swap(Task_Address* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Task_Address* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Task_Address* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Task_Address>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Task_Address& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Task_Address& from) { Task_Address::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Task_Address* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "palm.email.v1.Task.Address"; }

 protected:
  explicit Task_Address(::google::protobuf::Arena* arena);
  Task_Address(::google::protobuf::Arena* arena, const Task_Address& from);
  Task_Address(::google::protobuf::Arena* arena, Task_Address&& from) noexcept
      : Task_Address(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------
  enum : int {
    kNameFieldNumber = 1,
    kEmailFieldNumber = 2,
  };
  // string name = 1;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* value);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // string email = 2;
  void clear_email() ;
  const std::string& email() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_email(Arg_&& arg, Args_... args);
  std::string* mutable_email();
  PROTOBUF_NODISCARD std::string* release_email();
  void set_allocated_email(std::string* value);

  private:
  const std::string& _internal_email() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_email(
      const std::string& value);
  std::string* _internal_mutable_email();

  public:
  // @@protoc_insertion_point(class_scope:palm.email.v1.Task.Address)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      1, 2, 0,
      44, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Task_Address& from_msg);
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::google::protobuf::internal::ArenaStringPtr email_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_email_2eproto;
};
// -------------------------------------------------------------------

class Task final : public ::google::protobuf::Message
/* @@protoc_insertion_point(class_definition:palm.email.v1.Task) */ {
 public:
  inline Task() : Task(nullptr) {}
  ~Task() PROTOBUF_FINAL;

#if defined(PROTOBUF_CUSTOM_VTABLE)
  void operator delete(Task* msg, std::destroying_delete_t) {
    SharedDtor(*msg);
    ::google::protobuf::internal::SizedDelete(msg, sizeof(Task));
  }
#endif

  template <typename = void>
  explicit PROTOBUF_CONSTEXPR Task(
      ::google::protobuf::internal::ConstantInitialized);

  inline Task(const Task& from) : Task(nullptr, from) {}
  inline Task(Task&& from) noexcept
      : Task(nullptr, std::move(from)) {}
  inline Task& operator=(const Task& from) {
    CopyFrom(from);
    return *this;
  }
  inline Task& operator=(Task&& from) noexcept {
    if (this == &from) return *this;
    if (::google::protobuf::internal::CanMoveWithInternalSwap(GetArena(), from.GetArena())) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields()
      ABSL_ATTRIBUTE_LIFETIME_BOUND {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Task& default_instance() {
    return *internal_default_instance();
  }
  static inline const Task* internal_default_instance() {
    return reinterpret_cast<const Task*>(
        &_Task_default_instance_);
  }
  static constexpr int kIndexInFileMessages = 3;
  friend void swap(Task& a, Task& b) { a.Swap(&b); }
  inline void Swap(Task* other) {
    if (other == this) return;
    if (::google::protobuf::internal::CanUseInternalSwap(GetArena(), other->GetArena())) {
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Task* other) {
    if (other == this) return;
    ABSL_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Task* New(::google::protobuf::Arena* arena = nullptr) const {
    return ::google::protobuf::Message::DefaultConstruct<Task>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Task& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom(const Task& from) { Task::MergeImpl(*this, from); }

  private:
  static void MergeImpl(
      ::google::protobuf::MessageLite& to_msg,
      const ::google::protobuf::MessageLite& from_msg);

  public:
  bool IsInitialized() const {
    return true;
  }
  ABSL_ATTRIBUTE_REINITIALIZES void Clear() PROTOBUF_FINAL;
  #if defined(PROTOBUF_CUSTOM_VTABLE)
  private:
  static ::size_t ByteSizeLong(const ::google::protobuf::MessageLite& msg);
  static ::uint8_t* _InternalSerialize(
      const MessageLite& msg, ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream);

  public:
  ::size_t ByteSizeLong() const { return ByteSizeLong(*this); }
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const {
    return _InternalSerialize(*this, target, stream);
  }
  #else   // PROTOBUF_CUSTOM_VTABLE
  ::size_t ByteSizeLong() const final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target,
      ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  #endif  // PROTOBUF_CUSTOM_VTABLE
  int GetCachedSize() const { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  static void SharedDtor(MessageLite& self);
  void InternalSwap(Task* other);
 private:
  template <typename T>
  friend ::absl::string_view(
      ::google::protobuf::internal::GetAnyMessageName)();
  static ::absl::string_view FullMessageName() { return "palm.email.v1.Task"; }

 protected:
  explicit Task(::google::protobuf::Arena* arena);
  Task(::google::protobuf::Arena* arena, const Task& from);
  Task(::google::protobuf::Arena* arena, Task&& from) noexcept
      : Task(arena) {
    *this = ::std::move(from);
  }
  const ::google::protobuf::internal::ClassData* GetClassData() const PROTOBUF_FINAL;
  static void* PlacementNew_(const void*, void* mem,
                             ::google::protobuf::Arena* arena);
  static constexpr auto InternalNewImpl_();
  static const ::google::protobuf::internal::ClassDataFull _class_data_;

 public:
  ::google::protobuf::Metadata GetMetadata() const;
  // nested types ----------------------------------------------------
  using Address = Task_Address;
  using Body = Task_Body;
  using Attachment = Task_Attachment;

  // accessors -------------------------------------------------------
  enum : int {
    kCcFieldNumber = 2,
    kBccFieldNumber = 3,
    kAttachmentsFieldNumber = 13,
    kSubjectFieldNumber = 11,
    kToFieldNumber = 1,
    kBodyFieldNumber = 12,
  };
  // repeated .palm.email.v1.Task.Address cc = 2;
  int cc_size() const;
  private:
  int _internal_cc_size() const;

  public:
  void clear_cc() ;
  ::palm::email::v1::Task_Address* mutable_cc(int index);
  ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>* mutable_cc();

  private:
  const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>& _internal_cc() const;
  ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>* _internal_mutable_cc();
  public:
  const ::palm::email::v1::Task_Address& cc(int index) const;
  ::palm::email::v1::Task_Address* add_cc();
  const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>& cc() const;
  // repeated .palm.email.v1.Task.Address bcc = 3;
  int bcc_size() const;
  private:
  int _internal_bcc_size() const;

  public:
  void clear_bcc() ;
  ::palm::email::v1::Task_Address* mutable_bcc(int index);
  ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>* mutable_bcc();

  private:
  const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>& _internal_bcc() const;
  ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>* _internal_mutable_bcc();
  public:
  const ::palm::email::v1::Task_Address& bcc(int index) const;
  ::palm::email::v1::Task_Address* add_bcc();
  const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>& bcc() const;
  // repeated .palm.email.v1.Task.Attachment attachments = 13;
  int attachments_size() const;
  private:
  int _internal_attachments_size() const;

  public:
  void clear_attachments() ;
  ::palm::email::v1::Task_Attachment* mutable_attachments(int index);
  ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Attachment>* mutable_attachments();

  private:
  const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Attachment>& _internal_attachments() const;
  ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Attachment>* _internal_mutable_attachments();
  public:
  const ::palm::email::v1::Task_Attachment& attachments(int index) const;
  ::palm::email::v1::Task_Attachment* add_attachments();
  const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Attachment>& attachments() const;
  // string subject = 11;
  void clear_subject() ;
  const std::string& subject() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_subject(Arg_&& arg, Args_... args);
  std::string* mutable_subject();
  PROTOBUF_NODISCARD std::string* release_subject();
  void set_allocated_subject(std::string* value);

  private:
  const std::string& _internal_subject() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_subject(
      const std::string& value);
  std::string* _internal_mutable_subject();

  public:
  // .palm.email.v1.Task.Address to = 1;
  bool has_to() const;
  void clear_to() ;
  const ::palm::email::v1::Task_Address& to() const;
  PROTOBUF_NODISCARD ::palm::email::v1::Task_Address* release_to();
  ::palm::email::v1::Task_Address* mutable_to();
  void set_allocated_to(::palm::email::v1::Task_Address* value);
  void unsafe_arena_set_allocated_to(::palm::email::v1::Task_Address* value);
  ::palm::email::v1::Task_Address* unsafe_arena_release_to();

  private:
  const ::palm::email::v1::Task_Address& _internal_to() const;
  ::palm::email::v1::Task_Address* _internal_mutable_to();

  public:
  // .palm.email.v1.Task.Body body = 12;
  bool has_body() const;
  void clear_body() ;
  const ::palm::email::v1::Task_Body& body() const;
  PROTOBUF_NODISCARD ::palm::email::v1::Task_Body* release_body();
  ::palm::email::v1::Task_Body* mutable_body();
  void set_allocated_body(::palm::email::v1::Task_Body* value);
  void unsafe_arena_set_allocated_body(::palm::email::v1::Task_Body* value);
  ::palm::email::v1::Task_Body* unsafe_arena_release_body();

  private:
  const ::palm::email::v1::Task_Body& _internal_body() const;
  ::palm::email::v1::Task_Body* _internal_mutable_body();

  public:
  // @@protoc_insertion_point(class_scope:palm.email.v1.Task)
 private:
  class _Internal;
  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<
      3, 6, 5,
      34, 2>
      _table_;

  friend class ::google::protobuf::MessageLite;
  friend class ::google::protobuf::Arena;
  template <typename T>
  friend class ::google::protobuf::Arena::InternalHelper;
  using InternalArenaConstructable_ = void;
  using DestructorSkippable_ = void;
  struct Impl_ {
    inline explicit constexpr Impl_(
        ::google::protobuf::internal::ConstantInitialized) noexcept;
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena);
    inline explicit Impl_(::google::protobuf::internal::InternalVisibility visibility,
                          ::google::protobuf::Arena* arena, const Impl_& from,
                          const Task& from_msg);
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::palm::email::v1::Task_Address > cc_;
    ::google::protobuf::RepeatedPtrField< ::palm::email::v1::Task_Address > bcc_;
    ::google::protobuf::RepeatedPtrField< ::palm::email::v1::Task_Attachment > attachments_;
    ::google::protobuf::internal::ArenaStringPtr subject_;
    ::palm::email::v1::Task_Address* to_;
    ::palm::email::v1::Task_Body* body_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_email_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Task_Address

// string name = 1;
inline void Task_Address::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Task_Address::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.Address.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Task_Address::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:palm.email.v1.Task.Address.name)
}
inline std::string* Task_Address::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:palm.email.v1.Task.Address.name)
  return _s;
}
inline const std::string& Task_Address::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Task_Address::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* Task_Address::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* Task_Address::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:palm.email.v1.Task.Address.name)
  return _impl_.name_.Release();
}
inline void Task_Address::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:palm.email.v1.Task.Address.name)
}

// string email = 2;
inline void Task_Address::clear_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.ClearToEmpty();
}
inline const std::string& Task_Address::email() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.Address.email)
  return _internal_email();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Task_Address::set_email(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:palm.email.v1.Task.Address.email)
}
inline std::string* Task_Address::mutable_email() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_email();
  // @@protoc_insertion_point(field_mutable:palm.email.v1.Task.Address.email)
  return _s;
}
inline const std::string& Task_Address::_internal_email() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.email_.Get();
}
inline void Task_Address::_internal_set_email(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.Set(value, GetArena());
}
inline std::string* Task_Address::_internal_mutable_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.email_.Mutable( GetArena());
}
inline std::string* Task_Address::release_email() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:palm.email.v1.Task.Address.email)
  return _impl_.email_.Release();
}
inline void Task_Address::set_allocated_email(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.email_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.email_.IsDefault()) {
    _impl_.email_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:palm.email.v1.Task.Address.email)
}

// -------------------------------------------------------------------

// Task_Body

// string content = 1;
inline void Task_Body::clear_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.ClearToEmpty();
}
inline const std::string& Task_Body::content() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.Body.content)
  return _internal_content();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Task_Body::set_content(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:palm.email.v1.Task.Body.content)
}
inline std::string* Task_Body::mutable_content() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:palm.email.v1.Task.Body.content)
  return _s;
}
inline const std::string& Task_Body::_internal_content() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.content_.Get();
}
inline void Task_Body::_internal_set_content(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.Set(value, GetArena());
}
inline std::string* Task_Body::_internal_mutable_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.content_.Mutable( GetArena());
}
inline std::string* Task_Body::release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:palm.email.v1.Task.Body.content)
  return _impl_.content_.Release();
}
inline void Task_Body::set_allocated_content(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:palm.email.v1.Task.Body.content)
}

// bool html = 2;
inline void Task_Body::clear_html() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.html_ = false;
}
inline bool Task_Body::html() const {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.Body.html)
  return _internal_html();
}
inline void Task_Body::set_html(bool value) {
  _internal_set_html(value);
  // @@protoc_insertion_point(field_set:palm.email.v1.Task.Body.html)
}
inline bool Task_Body::_internal_html() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.html_;
}
inline void Task_Body::_internal_set_html(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.html_ = value;
}

// -------------------------------------------------------------------

// Task_Attachment

// string name = 1;
inline void Task_Attachment::clear_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Task_Attachment::name() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.Attachment.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Task_Attachment::set_name(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:palm.email.v1.Task.Attachment.name)
}
inline std::string* Task_Attachment::mutable_name() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:palm.email.v1.Task.Attachment.name)
  return _s;
}
inline const std::string& Task_Attachment::_internal_name() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.name_.Get();
}
inline void Task_Attachment::_internal_set_name(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.Set(value, GetArena());
}
inline std::string* Task_Attachment::_internal_mutable_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.name_.Mutable( GetArena());
}
inline std::string* Task_Attachment::release_name() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:palm.email.v1.Task.Attachment.name)
  return _impl_.name_.Release();
}
inline void Task_Attachment::set_allocated_name(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.name_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.name_.IsDefault()) {
    _impl_.name_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:palm.email.v1.Task.Attachment.name)
}

// bytes content = 2;
inline void Task_Attachment::clear_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.ClearToEmpty();
}
inline const std::string& Task_Attachment::content() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.Attachment.content)
  return _internal_content();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Task_Attachment::set_content(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.SetBytes(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:palm.email.v1.Task.Attachment.content)
}
inline std::string* Task_Attachment::mutable_content() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_content();
  // @@protoc_insertion_point(field_mutable:palm.email.v1.Task.Attachment.content)
  return _s;
}
inline const std::string& Task_Attachment::_internal_content() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.content_.Get();
}
inline void Task_Attachment::_internal_set_content(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.Set(value, GetArena());
}
inline std::string* Task_Attachment::_internal_mutable_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.content_.Mutable( GetArena());
}
inline std::string* Task_Attachment::release_content() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:palm.email.v1.Task.Attachment.content)
  return _impl_.content_.Release();
}
inline void Task_Attachment::set_allocated_content(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.content_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.content_.IsDefault()) {
    _impl_.content_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:palm.email.v1.Task.Attachment.content)
}

// bool inline = 3;
inline void Task_Attachment::clear_inline_() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.inline__ = false;
}
inline bool Task_Attachment::inline_() const {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.Attachment.inline)
  return _internal_inline_();
}
inline void Task_Attachment::set_inline_(bool value) {
  _internal_set_inline_(value);
  // @@protoc_insertion_point(field_set:palm.email.v1.Task.Attachment.inline)
}
inline bool Task_Attachment::_internal_inline_() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.inline__;
}
inline void Task_Attachment::_internal_set_inline_(bool value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.inline__ = value;
}

// -------------------------------------------------------------------

// Task

// .palm.email.v1.Task.Address to = 1;
inline bool Task::has_to() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.to_ != nullptr);
  return value;
}
inline void Task::clear_to() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.to_ != nullptr) _impl_.to_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::palm::email::v1::Task_Address& Task::_internal_to() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::palm::email::v1::Task_Address* p = _impl_.to_;
  return p != nullptr ? *p : reinterpret_cast<const ::palm::email::v1::Task_Address&>(::palm::email::v1::_Task_Address_default_instance_);
}
inline const ::palm::email::v1::Task_Address& Task::to() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.to)
  return _internal_to();
}
inline void Task::unsafe_arena_set_allocated_to(::palm::email::v1::Task_Address* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.to_);
  }
  _impl_.to_ = reinterpret_cast<::palm::email::v1::Task_Address*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:palm.email.v1.Task.to)
}
inline ::palm::email::v1::Task_Address* Task::release_to() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::palm::email::v1::Task_Address* released = _impl_.to_;
  _impl_.to_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::palm::email::v1::Task_Address* Task::unsafe_arena_release_to() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:palm.email.v1.Task.to)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::palm::email::v1::Task_Address* temp = _impl_.to_;
  _impl_.to_ = nullptr;
  return temp;
}
inline ::palm::email::v1::Task_Address* Task::_internal_mutable_to() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.to_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::palm::email::v1::Task_Address>(GetArena());
    _impl_.to_ = reinterpret_cast<::palm::email::v1::Task_Address*>(p);
  }
  return _impl_.to_;
}
inline ::palm::email::v1::Task_Address* Task::mutable_to() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000001u;
  ::palm::email::v1::Task_Address* _msg = _internal_mutable_to();
  // @@protoc_insertion_point(field_mutable:palm.email.v1.Task.to)
  return _msg;
}
inline void Task::set_allocated_to(::palm::email::v1::Task_Address* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.to_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.to_ = reinterpret_cast<::palm::email::v1::Task_Address*>(value);
  // @@protoc_insertion_point(field_set_allocated:palm.email.v1.Task.to)
}

// repeated .palm.email.v1.Task.Address cc = 2;
inline int Task::_internal_cc_size() const {
  return _internal_cc().size();
}
inline int Task::cc_size() const {
  return _internal_cc_size();
}
inline void Task::clear_cc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.cc_.Clear();
}
inline ::palm::email::v1::Task_Address* Task::mutable_cc(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:palm.email.v1.Task.cc)
  return _internal_mutable_cc()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>* Task::mutable_cc()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:palm.email.v1.Task.cc)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_cc();
}
inline const ::palm::email::v1::Task_Address& Task::cc(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.cc)
  return _internal_cc().Get(index);
}
inline ::palm::email::v1::Task_Address* Task::add_cc() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::palm::email::v1::Task_Address* _add = _internal_mutable_cc()->Add();
  // @@protoc_insertion_point(field_add:palm.email.v1.Task.cc)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>& Task::cc() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:palm.email.v1.Task.cc)
  return _internal_cc();
}
inline const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>&
Task::_internal_cc() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.cc_;
}
inline ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>*
Task::_internal_mutable_cc() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.cc_;
}

// repeated .palm.email.v1.Task.Address bcc = 3;
inline int Task::_internal_bcc_size() const {
  return _internal_bcc().size();
}
inline int Task::bcc_size() const {
  return _internal_bcc_size();
}
inline void Task::clear_bcc() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.bcc_.Clear();
}
inline ::palm::email::v1::Task_Address* Task::mutable_bcc(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:palm.email.v1.Task.bcc)
  return _internal_mutable_bcc()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>* Task::mutable_bcc()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:palm.email.v1.Task.bcc)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_bcc();
}
inline const ::palm::email::v1::Task_Address& Task::bcc(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.bcc)
  return _internal_bcc().Get(index);
}
inline ::palm::email::v1::Task_Address* Task::add_bcc() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::palm::email::v1::Task_Address* _add = _internal_mutable_bcc()->Add();
  // @@protoc_insertion_point(field_add:palm.email.v1.Task.bcc)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>& Task::bcc() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:palm.email.v1.Task.bcc)
  return _internal_bcc();
}
inline const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>&
Task::_internal_bcc() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.bcc_;
}
inline ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Address>*
Task::_internal_mutable_bcc() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.bcc_;
}

// string subject = 11;
inline void Task::clear_subject() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.subject_.ClearToEmpty();
}
inline const std::string& Task::subject() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.subject)
  return _internal_subject();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Task::set_subject(Arg_&& arg,
                                                     Args_... args) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.subject_.Set(static_cast<Arg_&&>(arg), args..., GetArena());
  // @@protoc_insertion_point(field_set:palm.email.v1.Task.subject)
}
inline std::string* Task::mutable_subject() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  std::string* _s = _internal_mutable_subject();
  // @@protoc_insertion_point(field_mutable:palm.email.v1.Task.subject)
  return _s;
}
inline const std::string& Task::_internal_subject() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.subject_.Get();
}
inline void Task::_internal_set_subject(const std::string& value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.subject_.Set(value, GetArena());
}
inline std::string* Task::_internal_mutable_subject() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _impl_.subject_.Mutable( GetArena());
}
inline std::string* Task::release_subject() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:palm.email.v1.Task.subject)
  return _impl_.subject_.Release();
}
inline void Task::set_allocated_subject(std::string* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.subject_.SetAllocated(value, GetArena());
  if (::google::protobuf::internal::DebugHardenForceCopyDefaultString() && _impl_.subject_.IsDefault()) {
    _impl_.subject_.Set("", GetArena());
  }
  // @@protoc_insertion_point(field_set_allocated:palm.email.v1.Task.subject)
}

// .palm.email.v1.Task.Body body = 12;
inline bool Task::has_body() const {
  bool value = (_impl_._has_bits_[0] & 0x00000002u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.body_ != nullptr);
  return value;
}
inline void Task::clear_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.body_ != nullptr) _impl_.body_->Clear();
  _impl_._has_bits_[0] &= ~0x00000002u;
}
inline const ::palm::email::v1::Task_Body& Task::_internal_body() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  const ::palm::email::v1::Task_Body* p = _impl_.body_;
  return p != nullptr ? *p : reinterpret_cast<const ::palm::email::v1::Task_Body&>(::palm::email::v1::_Task_Body_default_instance_);
}
inline const ::palm::email::v1::Task_Body& Task::body() const ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.body)
  return _internal_body();
}
inline void Task::unsafe_arena_set_allocated_body(::palm::email::v1::Task_Body* value) {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.body_);
  }
  _impl_.body_ = reinterpret_cast<::palm::email::v1::Task_Body*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:palm.email.v1.Task.body)
}
inline ::palm::email::v1::Task_Body* Task::release_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::palm::email::v1::Task_Body* released = _impl_.body_;
  _impl_.body_ = nullptr;
  if (::google::protobuf::internal::DebugHardenForceCopyInRelease()) {
    auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    if (GetArena() == nullptr) {
      delete old;
    }
  } else {
    if (GetArena() != nullptr) {
      released = ::google::protobuf::internal::DuplicateIfNonNull(released);
    }
  }
  return released;
}
inline ::palm::email::v1::Task_Body* Task::unsafe_arena_release_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  // @@protoc_insertion_point(field_release:palm.email.v1.Task.body)

  _impl_._has_bits_[0] &= ~0x00000002u;
  ::palm::email::v1::Task_Body* temp = _impl_.body_;
  _impl_.body_ = nullptr;
  return temp;
}
inline ::palm::email::v1::Task_Body* Task::_internal_mutable_body() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.body_ == nullptr) {
    auto* p = ::google::protobuf::Message::DefaultConstruct<::palm::email::v1::Task_Body>(GetArena());
    _impl_.body_ = reinterpret_cast<::palm::email::v1::Task_Body*>(p);
  }
  return _impl_.body_;
}
inline ::palm::email::v1::Task_Body* Task::mutable_body() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  _impl_._has_bits_[0] |= 0x00000002u;
  ::palm::email::v1::Task_Body* _msg = _internal_mutable_body();
  // @@protoc_insertion_point(field_mutable:palm.email.v1.Task.body)
  return _msg;
}
inline void Task::set_allocated_body(::palm::email::v1::Task_Body* value) {
  ::google::protobuf::Arena* message_arena = GetArena();
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (message_arena == nullptr) {
    delete (_impl_.body_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena = (value)->GetArena();
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000002u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000002u;
  }

  _impl_.body_ = reinterpret_cast<::palm::email::v1::Task_Body*>(value);
  // @@protoc_insertion_point(field_set_allocated:palm.email.v1.Task.body)
}

// repeated .palm.email.v1.Task.Attachment attachments = 13;
inline int Task::_internal_attachments_size() const {
  return _internal_attachments().size();
}
inline int Task::attachments_size() const {
  return _internal_attachments_size();
}
inline void Task::clear_attachments() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.attachments_.Clear();
}
inline ::palm::email::v1::Task_Attachment* Task::mutable_attachments(int index)
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable:palm.email.v1.Task.attachments)
  return _internal_mutable_attachments()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Attachment>* Task::mutable_attachments()
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_mutable_list:palm.email.v1.Task.attachments)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  return _internal_mutable_attachments();
}
inline const ::palm::email::v1::Task_Attachment& Task::attachments(int index) const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_get:palm.email.v1.Task.attachments)
  return _internal_attachments().Get(index);
}
inline ::palm::email::v1::Task_Attachment* Task::add_attachments() ABSL_ATTRIBUTE_LIFETIME_BOUND {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::palm::email::v1::Task_Attachment* _add = _internal_mutable_attachments()->Add();
  // @@protoc_insertion_point(field_add:palm.email.v1.Task.attachments)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Attachment>& Task::attachments() const
    ABSL_ATTRIBUTE_LIFETIME_BOUND {
  // @@protoc_insertion_point(field_list:palm.email.v1.Task.attachments)
  return _internal_attachments();
}
inline const ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Attachment>&
Task::_internal_attachments() const {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return _impl_.attachments_;
}
inline ::google::protobuf::RepeatedPtrField<::palm::email::v1::Task_Attachment>*
Task::_internal_mutable_attachments() {
  ::google::protobuf::internal::TSanRead(&_impl_);
  return &_impl_.attachments_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace v1
}  // namespace email
}  // namespace palm


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // email_2eproto_2epb_2eh
