[package]
name = "wisteria"
version = "2026.7.21"
edition = "2024"
description = "An online education solution."

[dependencies]
tokio-stream = "0.1"
futures = "0.3"
log = "0.4"
juniper_graphql_ws = "0.5"
yaml_serde = "0.10"
env_logger = "0.11"
lettre = "0.11"
juniper = "0.17"
hyper = "1"
data-encoding = "2"
icu = "2"
tempfile = "3"
flatbuffers = "25"
flexbuffers = "25"

[dependencies.juniper_axum]
version = "0.3"
features = ["subscriptions"]

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.axum]
version = "0.8"
features = ["macros"]

[dependencies.chrono-tz]
version = "0.10"
features = ["serde"]

[dependencies.axum-extra]
version = "0.12"
features = ["cookie-private", "cookie-signed"]

[dependencies.validator]
version = "0.21"
features = ["derive"]

[dependencies.strum]
version = "0.28"
features = ["derive"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.diesel]
version = "2"
default-features = false

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.belladonna]
path = "../belladonna"

[dependencies.hyacinth]
path = "../hyacinth"

[dependencies.portal]
path = "../portal"

[dependencies.cms]
path = "../cms"

[dependencies.forum]
path = "../forum"

[dependencies.curricula]
path = "../curricula"

[dependencies.questionnaire]
path = "../questionnaire"

[dependencies.accounting]
path = "../accounting"

[dependencies.lavender]
path = "../lavender"

[dependencies.camellia]
path = "../camellia"
