- name: Install packages
  become: true
  ansible.builtin.apt:
    pkg:
      - tree
      - imagemagick
      - ffmpeg
      - dia
      - vlc
      - notepadnext
      - chromium-browser
      - microsoft-edge-stable
      - wechat-devtools
      - wechat-beta
      - linuxqq
      - kylin-tencentmeeting
      - wps-office
      - virtualbox-7.0

- include_tasks: third.yml
