[program:postgresql]
directory=/usr/share/elasticsearch
command=/usr/share/elasticsearch/bin/elasticsearch -p ${PID_DIR}/elasticsearch.pid
autostart=true
user=elasticsearch
group=elasticsearch
autorestart=true
loglevel=info
environment=ES_HOME=/usr/share/elasticsearch
environment=ES_PATH_CONF=/etc/elasticsearch
environment=PID_DIR=/run/elasticsearch
environment=ES_SD_NOTIFY=true
