[program:postgresql]
directory=/usr/lib/postgresql/13
command=/usr/lib/postgresql/13/bin/postgres -D /var/lib/postgresql/13/main --config-file=/etc/postgresql/13/main/postgresql.conf
autostart=true
user=postgres
autorestart=true
loglevel=info
