[program:rabbitmq]
directory=%(ENV_RABBITMQ_HOME)s
command=%(ENV_RABBITMQ_HOME)s/sbin/rabbitmq-server
autostart=true
user=deploy
autorestart=true
loglevel=info
environment=RABBITMQ_HOME="/home/deploy/local/rabbitmq_server"
