[postgresql]
host = "127.0.0.1"
port = 5432
user = "www"
password = "change-me"
dbname = "almond"

[redis]
namespace = "almond"

[[redis.nodes]]
host = "127.0.0.1"
port = 6371

[[redis.nodes]]
host = "127.0.0.1"
port = 6372

[[redis.nodes]]
host = "127.0.0.1"
port = 6373

[[redis.nodes]]
host = "127.0.0.1"
port = 6374

[[redis.nodes]]
host = "127.0.0.1"
port = 6375
