// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: casbin.proto
// Protobuf Java Version: 4.29.5

package com.github.saturn_xiv.palm.plugins.casbin.v1;

public interface ObjectOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.casbin.v1.Object)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string type = 1;</code>
   * @return The type.
   */
  java.lang.String getType();
  /**
   * <code>string type = 1;</code>
   * @return The bytes for type.
   */
  com.google.protobuf.ByteString
      getTypeBytes();

  /**
   * <code>uint32 id = 11;</code>
   * @return Whether the id field is set.
   */
  boolean hasId();
  /**
   * <code>uint32 id = 11;</code>
   * @return The id.
   */
  int getId();

  /**
   * <code>string code = 12;</code>
   * @return Whether the code field is set.
   */
  boolean hasCode();
  /**
   * <code>string code = 12;</code>
   * @return The code.
   */
  java.lang.String getCode();
  /**
   * <code>string code = 12;</code>
   * @return The bytes for code.
   */
  com.google.protobuf.ByteString
      getCodeBytes();

  /**
   * <code>.google.protobuf.Empty empty = 13;</code>
   * @return Whether the empty field is set.
   */
  boolean hasEmpty();
  /**
   * <code>.google.protobuf.Empty empty = 13;</code>
   * @return The empty.
   */
  com.google.protobuf.Empty getEmpty();
  /**
   * <code>.google.protobuf.Empty empty = 13;</code>
   */
  com.google.protobuf.EmptyOrBuilder getEmptyOrBuilder();

  com.github.saturn_xiv.palm.plugins.casbin.v1.Object.ByCase getByCase();
}
