- name: OpenSearch node
  hosts: all
  roles:
    - opensearch
  environment:
    # http_proxy: "http://172.26.176.222:8000"
    # https_proxy: "http://172.26.176.222:8000"
    # no_proxy: "localhost,127.0.0.1,172.26.176.0/20"
