// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: portal.proto
// Protobuf Java Version: 4.29.5

package com.github.saturn_xiv.palm.plugins.portal.v1;

public interface IdRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.portal.v1.IdRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   * @return The id.
   */
  int getId();
}
