[package]
name = "phlox"
version = "2026.3.29"
edition = "2024"

[dependencies]
axum = "0.8"
rabbitmq-stream-client = "0.11"
tonic = "0.14"
minio = "0.3"
hyper = "1"
data-encoding = "2"
opensearch = "2"
lapin = "4"
flexbuffers = "25"

[dependencies.rand]
version = "0.10"
features = ["thread_rng"]

[dependencies.reqwest]
version = "0.13"
features = ["json"]

[dependencies.redis]
version = "1"
features = ["r2d2"]

[dependencies.uuid]
version = "1"
features = ["v4", "serde"]

[dependencies.diesel]
version = "2"
default-features = false
features = ["r2d2", "postgres", "sqlite", "extras", "huge-tables"] # "mysql",

[dependencies.libsqlite3-sys]
version = "*"
features = ["bundled"]

# [dependencies.mysqlclient-sys]
# version = "*"
# features = ["bundled"]

[dependencies.pq-sys]
version = "*"
features = ["bundled"]

[dependencies.openssl-sys]
version = "*"
features = ["vendored"]
