[package]
name = "phlox"
version = "2025.5.23"
edition = "2024"
description = "A total free online education solution."

[dependencies]
env_logger = "0.11"
clap = "4"

[dependencies.diesel]
version = "2"
default-features = false
features = ["postgres", "extras", "huge-tables"]

[dependencies.thrift]
git = "https://github.com/apache/thrift.git"
tag = "v0.21.0"

[dependencies.fig]
path = "../fig"
