[program:elasticsearch]
directory=%(ENV_ES_HOME)s
command=%(ENV_ES_HOME)s/bin/elasticsearch
autostart=true
user=deploy
autorestart=true
loglevel=info
environment=ES_HEAP_SIZE="2G",ES_HOME="/home/deploy/local/elasticsearch"
