[program:redis-cluster-1]
directory=/var/lib/redis/cluster-1
command=/usr/bin/redis-server /etc/redis/cluster-1.conf
autostart=true
user=root
autorestart=true
loglevel=info

[program:redis-cluster-2]
directory=/var/lib/redis/cluster-2
command=/usr/bin/redis-server /etc/redis/cluster-2.conf
autostart=true
user=root
autorestart=true
loglevel=info

[program:redis-cluster-3]
directory=/var/lib/redis/cluster-3
command=/usr/bin/redis-server /etc/redis/cluster-3.conf
autostart=true
user=root
autorestart=true
loglevel=info

[program:redis-cluster-4]
directory=/var/lib/redis/cluster-4
command=/usr/bin/redis-server /etc/redis/cluster-4.conf
autostart=true
user=root
autorestart=true
loglevel=info

[program:redis-cluster-5]
directory=/var/lib/redis/cluster-5
command=/usr/bin/redis-server /etc/redis/cluster-5.conf
autostart=true
user=root
autorestart=true
loglevel=info

[program:redis-cluster-6]
directory=/var/lib/redis/cluster-6
command=/usr/bin/redis-server /etc/redis/cluster-6.conf
autostart=true
user=root
autorestart=true
loglevel=info
