[package]
name = "camellia"
version = "2026.9.8"
edition = "2024"
description = "E-book management."

[dependencies]
log = "0.4"
juniper = "0.17"
hyper = "1"
data-encoding = "2"

[dependencies.chrono]
version = "0.4"
features = ["serde"]

[dependencies.axum]
version = "0.8"
features = ["macros"]

[dependencies.chrono-tz]
version = "0.10"
features = ["serde"]

[dependencies.reqwest]
version = "0.13"
features = ["json"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.uuid]
version = "1"
features = ["v4", "serde"]

[dependencies.portal]
path = "../portal"
