/**
 * @fileoverview gRPC-Web generated client stub for palm.atropa.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.4.2
// 	protoc              v5.26.1
// source: atropa.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as google_protobuf_empty_pb from 'google-protobuf/google/protobuf/empty_pb';
import * as atropa_pb from './atropa_pb';


export class PolicyClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorHas = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/Has',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyHasRequest,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.PolicyHasRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  has(
    request: atropa_pb.PolicyHasRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  has(
    request: atropa_pb.PolicyHasRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  has(
    request: atropa_pb.PolicyHasRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/Has',
        request,
        metadata || {},
        this.methodDescriptorHas,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/Has',
    request,
    metadata || {},
    this.methodDescriptorHas);
  }

  methodDescriptorCan = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/Can',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyCanRequest,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.PolicyCanRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  can(
    request: atropa_pb.PolicyCanRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  can(
    request: atropa_pb.PolicyCanRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  can(
    request: atropa_pb.PolicyCanRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/Can',
        request,
        metadata || {},
        this.methodDescriptorCan,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/Can',
    request,
    metadata || {},
    this.methodDescriptorCan);
  }

  methodDescriptorDeleteUser = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/DeleteUser',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyUsersResponse.Item,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.PolicyUsersResponse.Item) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/DeleteUser',
        request,
        metadata || {},
        this.methodDescriptorDeleteUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/DeleteUser',
    request,
    metadata || {},
    this.methodDescriptorDeleteUser);
  }

  methodDescriptorDeleteRole = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/DeleteRole',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyRolesResponse.Item,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.PolicyRolesResponse.Item) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/DeleteRole',
        request,
        metadata || {},
        this.methodDescriptorDeleteRole,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/DeleteRole',
    request,
    metadata || {},
    this.methodDescriptorDeleteRole);
  }

  methodDescriptorGetRolesForUser = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/GetRolesForUser',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyUsersResponse.Item,
    atropa_pb.PolicyRolesResponse,
    (request: atropa_pb.PolicyUsersResponse.Item) => {
      return request.serializeBinary();
    },
    atropa_pb.PolicyRolesResponse.deserializeBinary
  );

  getRolesForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.PolicyRolesResponse>;

  getRolesForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyRolesResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.PolicyRolesResponse>;

  getRolesForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyRolesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/GetRolesForUser',
        request,
        metadata || {},
        this.methodDescriptorGetRolesForUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/GetRolesForUser',
    request,
    metadata || {},
    this.methodDescriptorGetRolesForUser);
  }

  methodDescriptorGetImplicitRolesForUser = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/GetImplicitRolesForUser',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyUsersResponse.Item,
    atropa_pb.PolicyRolesResponse,
    (request: atropa_pb.PolicyUsersResponse.Item) => {
      return request.serializeBinary();
    },
    atropa_pb.PolicyRolesResponse.deserializeBinary
  );

  getImplicitRolesForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.PolicyRolesResponse>;

  getImplicitRolesForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyRolesResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.PolicyRolesResponse>;

  getImplicitRolesForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyRolesResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/GetImplicitRolesForUser',
        request,
        metadata || {},
        this.methodDescriptorGetImplicitRolesForUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/GetImplicitRolesForUser',
    request,
    metadata || {},
    this.methodDescriptorGetImplicitRolesForUser);
  }

  methodDescriptorGetUsersForRole = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/GetUsersForRole',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyRolesResponse.Item,
    atropa_pb.PolicyUsersResponse,
    (request: atropa_pb.PolicyRolesResponse.Item) => {
      return request.serializeBinary();
    },
    atropa_pb.PolicyUsersResponse.deserializeBinary
  );

  getUsersForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.PolicyUsersResponse>;

  getUsersForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyUsersResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.PolicyUsersResponse>;

  getUsersForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyUsersResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/GetUsersForRole',
        request,
        metadata || {},
        this.methodDescriptorGetUsersForRole,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/GetUsersForRole',
    request,
    metadata || {},
    this.methodDescriptorGetUsersForRole);
  }

  methodDescriptorGetImplicitUsersForRole = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/GetImplicitUsersForRole',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyRolesResponse.Item,
    atropa_pb.PolicyUsersResponse,
    (request: atropa_pb.PolicyRolesResponse.Item) => {
      return request.serializeBinary();
    },
    atropa_pb.PolicyUsersResponse.deserializeBinary
  );

  getImplicitUsersForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.PolicyUsersResponse>;

  getImplicitUsersForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyUsersResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.PolicyUsersResponse>;

  getImplicitUsersForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyUsersResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/GetImplicitUsersForRole',
        request,
        metadata || {},
        this.methodDescriptorGetImplicitUsersForRole,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/GetImplicitUsersForRole',
    request,
    metadata || {},
    this.methodDescriptorGetImplicitUsersForRole);
  }

  methodDescriptorAddRolesForUser = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/AddRolesForUser',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyRolesForUserRequest,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.PolicyRolesForUserRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  addRolesForUser(
    request: atropa_pb.PolicyRolesForUserRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  addRolesForUser(
    request: atropa_pb.PolicyRolesForUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  addRolesForUser(
    request: atropa_pb.PolicyRolesForUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/AddRolesForUser',
        request,
        metadata || {},
        this.methodDescriptorAddRolesForUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/AddRolesForUser',
    request,
    metadata || {},
    this.methodDescriptorAddRolesForUser);
  }

  methodDescriptorDeleteRolesForUser = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/DeleteRolesForUser',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyRolesForUserRequest,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.PolicyRolesForUserRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deleteRolesForUser(
    request: atropa_pb.PolicyRolesForUserRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deleteRolesForUser(
    request: atropa_pb.PolicyRolesForUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deleteRolesForUser(
    request: atropa_pb.PolicyRolesForUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/DeleteRolesForUser',
        request,
        metadata || {},
        this.methodDescriptorDeleteRolesForUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/DeleteRolesForUser',
    request,
    metadata || {},
    this.methodDescriptorDeleteRolesForUser);
  }

  methodDescriptorGetPermissionsForUser = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/GetPermissionsForUser',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyUsersResponse.Item,
    atropa_pb.PolicyPermissionsResponse,
    (request: atropa_pb.PolicyUsersResponse.Item) => {
      return request.serializeBinary();
    },
    atropa_pb.PolicyPermissionsResponse.deserializeBinary
  );

  getPermissionsForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.PolicyPermissionsResponse>;

  getPermissionsForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyPermissionsResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.PolicyPermissionsResponse>;

  getPermissionsForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyPermissionsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/GetPermissionsForUser',
        request,
        metadata || {},
        this.methodDescriptorGetPermissionsForUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/GetPermissionsForUser',
    request,
    metadata || {},
    this.methodDescriptorGetPermissionsForUser);
  }

  methodDescriptorGetImplicitPermissionsForUser = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/GetImplicitPermissionsForUser',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyUsersResponse.Item,
    atropa_pb.PolicyPermissionsResponse,
    (request: atropa_pb.PolicyUsersResponse.Item) => {
      return request.serializeBinary();
    },
    atropa_pb.PolicyPermissionsResponse.deserializeBinary
  );

  getImplicitPermissionsForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.PolicyPermissionsResponse>;

  getImplicitPermissionsForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyPermissionsResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.PolicyPermissionsResponse>;

  getImplicitPermissionsForUser(
    request: atropa_pb.PolicyUsersResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyPermissionsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/GetImplicitPermissionsForUser',
        request,
        metadata || {},
        this.methodDescriptorGetImplicitPermissionsForUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/GetImplicitPermissionsForUser',
    request,
    metadata || {},
    this.methodDescriptorGetImplicitPermissionsForUser);
  }

  methodDescriptorAddPermissionsForUser = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/AddPermissionsForUser',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyPermissionsForUserRequest,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.PolicyPermissionsForUserRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  addPermissionsForUser(
    request: atropa_pb.PolicyPermissionsForUserRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  addPermissionsForUser(
    request: atropa_pb.PolicyPermissionsForUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  addPermissionsForUser(
    request: atropa_pb.PolicyPermissionsForUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/AddPermissionsForUser',
        request,
        metadata || {},
        this.methodDescriptorAddPermissionsForUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/AddPermissionsForUser',
    request,
    metadata || {},
    this.methodDescriptorAddPermissionsForUser);
  }

  methodDescriptorDeletePermissionsForUser = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/DeletePermissionsForUser',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyPermissionsForUserRequest,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.PolicyPermissionsForUserRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deletePermissionsForUser(
    request: atropa_pb.PolicyPermissionsForUserRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deletePermissionsForUser(
    request: atropa_pb.PolicyPermissionsForUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deletePermissionsForUser(
    request: atropa_pb.PolicyPermissionsForUserRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/DeletePermissionsForUser',
        request,
        metadata || {},
        this.methodDescriptorDeletePermissionsForUser,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/DeletePermissionsForUser',
    request,
    metadata || {},
    this.methodDescriptorDeletePermissionsForUser);
  }

  methodDescriptorGetPermissionsForRole = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/GetPermissionsForRole',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyRolesResponse.Item,
    atropa_pb.PolicyPermissionsResponse,
    (request: atropa_pb.PolicyRolesResponse.Item) => {
      return request.serializeBinary();
    },
    atropa_pb.PolicyPermissionsResponse.deserializeBinary
  );

  getPermissionsForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.PolicyPermissionsResponse>;

  getPermissionsForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyPermissionsResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.PolicyPermissionsResponse>;

  getPermissionsForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyPermissionsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/GetPermissionsForRole',
        request,
        metadata || {},
        this.methodDescriptorGetPermissionsForRole,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/GetPermissionsForRole',
    request,
    metadata || {},
    this.methodDescriptorGetPermissionsForRole);
  }

  methodDescriptorGetImplicitPermissionsForRole = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/GetImplicitPermissionsForRole',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyRolesResponse.Item,
    atropa_pb.PolicyPermissionsResponse,
    (request: atropa_pb.PolicyRolesResponse.Item) => {
      return request.serializeBinary();
    },
    atropa_pb.PolicyPermissionsResponse.deserializeBinary
  );

  getImplicitPermissionsForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.PolicyPermissionsResponse>;

  getImplicitPermissionsForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyPermissionsResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.PolicyPermissionsResponse>;

  getImplicitPermissionsForRole(
    request: atropa_pb.PolicyRolesResponse.Item,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.PolicyPermissionsResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/GetImplicitPermissionsForRole',
        request,
        metadata || {},
        this.methodDescriptorGetImplicitPermissionsForRole,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/GetImplicitPermissionsForRole',
    request,
    metadata || {},
    this.methodDescriptorGetImplicitPermissionsForRole);
  }

  methodDescriptorAddPermissionsForRole = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/AddPermissionsForRole',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyPermissionsForRoleRequest,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.PolicyPermissionsForRoleRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  addPermissionsForRole(
    request: atropa_pb.PolicyPermissionsForRoleRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  addPermissionsForRole(
    request: atropa_pb.PolicyPermissionsForRoleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  addPermissionsForRole(
    request: atropa_pb.PolicyPermissionsForRoleRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/AddPermissionsForRole',
        request,
        metadata || {},
        this.methodDescriptorAddPermissionsForRole,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/AddPermissionsForRole',
    request,
    metadata || {},
    this.methodDescriptorAddPermissionsForRole);
  }

  methodDescriptorDeletePermissionsForRole = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Policy/DeletePermissionsForRole',
    grpcWeb.MethodType.UNARY,
    atropa_pb.PolicyPermissionsForRoleRequest,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.PolicyPermissionsForRoleRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  deletePermissionsForRole(
    request: atropa_pb.PolicyPermissionsForRoleRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  deletePermissionsForRole(
    request: atropa_pb.PolicyPermissionsForRoleRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  deletePermissionsForRole(
    request: atropa_pb.PolicyPermissionsForRoleRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Policy/DeletePermissionsForRole',
        request,
        metadata || {},
        this.methodDescriptorDeletePermissionsForRole,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Policy/DeletePermissionsForRole',
    request,
    metadata || {},
    this.methodDescriptorDeletePermissionsForRole);
  }

}

export class S3Client {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorCreateBucket = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.S3/CreateBucket',
    grpcWeb.MethodType.UNARY,
    atropa_pb.S3CreateBucketRequest,
    atropa_pb.S3CreateBucketResponse,
    (request: atropa_pb.S3CreateBucketRequest) => {
      return request.serializeBinary();
    },
    atropa_pb.S3CreateBucketResponse.deserializeBinary
  );

  createBucket(
    request: atropa_pb.S3CreateBucketRequest,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.S3CreateBucketResponse>;

  createBucket(
    request: atropa_pb.S3CreateBucketRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.S3CreateBucketResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.S3CreateBucketResponse>;

  createBucket(
    request: atropa_pb.S3CreateBucketRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.S3CreateBucketResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.S3/CreateBucket',
        request,
        metadata || {},
        this.methodDescriptorCreateBucket,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.S3/CreateBucket',
    request,
    metadata || {},
    this.methodDescriptorCreateBucket);
  }

  methodDescriptorUpload = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.S3/Upload',
    grpcWeb.MethodType.UNARY,
    atropa_pb.S3UploadRequest,
    atropa_pb.S3UploadUrlResponse,
    (request: atropa_pb.S3UploadRequest) => {
      return request.serializeBinary();
    },
    atropa_pb.S3UploadUrlResponse.deserializeBinary
  );

  upload(
    request: atropa_pb.S3UploadRequest,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.S3UploadUrlResponse>;

  upload(
    request: atropa_pb.S3UploadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.S3UploadUrlResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.S3UploadUrlResponse>;

  upload(
    request: atropa_pb.S3UploadRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.S3UploadUrlResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.S3/Upload',
        request,
        metadata || {},
        this.methodDescriptorUpload,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.S3/Upload',
    request,
    metadata || {},
    this.methodDescriptorUpload);
  }

  methodDescriptorPermanentUrl = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.S3/PermanentUrl',
    grpcWeb.MethodType.UNARY,
    atropa_pb.S3UploadRequest,
    atropa_pb.S3UploadUrlResponse,
    (request: atropa_pb.S3UploadRequest) => {
      return request.serializeBinary();
    },
    atropa_pb.S3UploadUrlResponse.deserializeBinary
  );

  permanentUrl(
    request: atropa_pb.S3UploadRequest,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.S3UploadUrlResponse>;

  permanentUrl(
    request: atropa_pb.S3UploadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.S3UploadUrlResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.S3UploadUrlResponse>;

  permanentUrl(
    request: atropa_pb.S3UploadRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.S3UploadUrlResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.S3/PermanentUrl',
        request,
        metadata || {},
        this.methodDescriptorPermanentUrl,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.S3/PermanentUrl',
    request,
    metadata || {},
    this.methodDescriptorPermanentUrl);
  }

  methodDescriptorPresignedUrl = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.S3/PresignedUrl',
    grpcWeb.MethodType.UNARY,
    atropa_pb.S3UploadRequest,
    atropa_pb.S3UploadUrlResponse,
    (request: atropa_pb.S3UploadRequest) => {
      return request.serializeBinary();
    },
    atropa_pb.S3UploadUrlResponse.deserializeBinary
  );

  presignedUrl(
    request: atropa_pb.S3UploadRequest,
    metadata: grpcWeb.Metadata | null): Promise<atropa_pb.S3UploadUrlResponse>;

  presignedUrl(
    request: atropa_pb.S3UploadRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: atropa_pb.S3UploadUrlResponse) => void): grpcWeb.ClientReadableStream<atropa_pb.S3UploadUrlResponse>;

  presignedUrl(
    request: atropa_pb.S3UploadRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: atropa_pb.S3UploadUrlResponse) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.S3/PresignedUrl',
        request,
        metadata || {},
        this.methodDescriptorPresignedUrl,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.S3/PresignedUrl',
    request,
    metadata || {},
    this.methodDescriptorPresignedUrl);
  }

}

export class SmsClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSend = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Sms/Send',
    grpcWeb.MethodType.UNARY,
    atropa_pb.SmsSendRequest,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.SmsSendRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  send(
    request: atropa_pb.SmsSendRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  send(
    request: atropa_pb.SmsSendRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  send(
    request: atropa_pb.SmsSendRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Sms/Send',
        request,
        metadata || {},
        this.methodDescriptorSend,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Sms/Send',
    request,
    metadata || {},
    this.methodDescriptorSend);
  }

}

export class EmailClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorSend = new grpcWeb.MethodDescriptor(
    '/palm.atropa.v1.Email/Send',
    grpcWeb.MethodType.UNARY,
    atropa_pb.EmailSendRequest,
    google_protobuf_empty_pb.Empty,
    (request: atropa_pb.EmailSendRequest) => {
      return request.serializeBinary();
    },
    google_protobuf_empty_pb.Empty.deserializeBinary
  );

  send(
    request: atropa_pb.EmailSendRequest,
    metadata: grpcWeb.Metadata | null): Promise<google_protobuf_empty_pb.Empty>;

  send(
    request: atropa_pb.EmailSendRequest,
    metadata: grpcWeb.Metadata | null,
    callback: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void): grpcWeb.ClientReadableStream<google_protobuf_empty_pb.Empty>;

  send(
    request: atropa_pb.EmailSendRequest,
    metadata: grpcWeb.Metadata | null,
    callback?: (err: grpcWeb.RpcError,
               response: google_protobuf_empty_pb.Empty) => void) {
    if (callback !== undefined) {
      return this.client_.rpcCall(
        this.hostname_ +
          '/palm.atropa.v1.Email/Send',
        request,
        metadata || {},
        this.methodDescriptorSend,
        callback);
    }
    return this.client_.unaryCall(
    this.hostname_ +
      '/palm.atropa.v1.Email/Send',
    request,
    metadata || {},
    this.methodDescriptorSend);
  }

}

