ServerName localhost

#LoadModule headers_module modules/mod_headers.so
#LoadModule env_module modules/mod_env.so
LoadModule expires_module modules/mod_expires.so
#LoadModule version_module modules/mod_version.so
LoadModule rewrite_module modules/mod_rewrite.so

#ErrorLog /workspace/tmp/error.log
#CustomLog /workspace/tmp/access.log

Alias /bugzilla /var/www/bugzilla
<Directory /var/www/bugzilla>
  AddHandler cgi-script .cgi
  Options +ExecCGI
  DirectoryIndex index.cgi index.html
  AllowOverride All
</Directory>




