[package]
name = "hyacinth"
version = "2026.7.23"
edition = "2024"
description = "Generated protocols"

[dependencies]
grpc = "0.9"
grpc-protobuf = "0.9"
tonic = "0.14"
thrift = "0.24"
protobuf = "=4.34.0-release"
flatbuffers = "25"

[dependencies.diesel]
version = "2"
default-features = false
features = ["128-column-tables", "postgres", "chrono", "uuid"]

[dependencies.openssl]
version = "*"
features = ["vendored"]

[dependencies.pq-sys]
version = "*"
features = ["bundled"]
