[package]
name = "hyacinth"
version = "2026.7.26"
edition = "2024"
description = "Generated protocols"

[dependencies]
log = "0.4"
grpc = "0.9"
grpc-protobuf = "0.9"
lettre = "0.11"
tonic = "0.14"
protobuf = "=4.34.0-release"
flatbuffers = "25"
flexbuffers = "25"

[dependencies.diesel]
version = "2"
default-features = false
features = [
    "128-column-tables",
    "postgres",
    # "mysql",
    "sqlite",
    "chrono",
    "uuid",
    "r2d2",
]

[dependencies.libsqlite3-sys]
version = "*"
features = ["bundled"]

# [dependencies.mysqlclient-sys]
# version = "*"
# features = ["bundled"]

[dependencies.pq-sys]
version = "*"
features = ["bundled"]

[dependencies.openssl-sys]
version = "*"
features = ["vendored"]
