- name: Create deploy bin dir
  ansible.builtin.file:
    path: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/bin"
    mode: "0755"
    state: directory

- name: Upload fig
  become: true
  ansible.builtin.copy:
    src: "{{ app_workspace_dir }}/target/{{ app_fig_arch }}-unknown-linux-gnu/release/fig"
    dest: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/bin/"
    mode: "0755"

- name: Create tmp dir
  become: true
  ansible.builtin.file:
    path: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/tmp"
    owner: www-data
    group: www-data
    mode: "0750"
    state: directory

- name: Upload package.json
  ansible.builtin.copy:
    src: "{{ app_workspace_dir }}/fig/package.json"
    dest: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/"
    mode: "0644"

# - name: Install third packages
#   ansible.builtin.shell:
#     cmd: npm install
#     chdir: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/"

- name: Create a node_modules link
  ansible.builtin.file:
    src: "/var/lib/fig/{{ app_deploy_domain }}/node_modules"
    dest: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/node_modules"
    state: link

- name: Upload themes folder
  ansible.posix.synchronize:
    src: "{{ app_workspace_dir }}/petunia/themes"
    dest: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}"

- name: Upload locales folder
  ansible.posix.synchronize:
    src: "{{ app_workspace_dir }}/fig/locales"
    dest: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/"

- name: Upload assets folder
  ansible.posix.synchronize:
    src: "{{ app_workspace_dir }}/fig/assets"
    dest: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/"

- name: Upload db folder
  ansible.posix.synchronize:
    src: "{{ app_workspace_dir }}/fig/db/postgresql/"
    dest: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/db"

- name: Upload .env for db migrations
  become: true
  ansible.builtin.template:
    src: env.j2
    dest: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/db/.env"
    mode: "0440"
    owner: www-data
    group: www-data

- name: Upload config.toml
  become: true
  ansible.builtin.template:
    src: config.toml.j2
    dest: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/config.toml"
    owner: www-data
    group: www-data
    mode: "0400"

- name: Upload nginx.conf
  ansible.builtin.template:
    src: nginx.conf.j2
    dest: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}/www.{{ app_deploy_domain }}.conf"
    mode: "0644"

- name: Upload www service
  become: true
  ansible.builtin.template:
    src: systemd/www.conf.j2
    dest: "/usr/lib/systemd/system/www.{{ app_deploy_domain }}.service"
    mode: "0644"

- name: Upload email-worker service
  become: true
  ansible.builtin.template:
    src: systemd/email-worker.conf.j2
    dest: "/usr/lib/systemd/system/email.worker.{{ app_deploy_domain }}.service"
    mode: "0644"

- name: Create a current link
  ansible.builtin.file:
    src: "/var/lib/fig/{{ app_deploy_domain }}/{{ app_deploy_version }}"
    dest: "/var/lib/fig/{{ app_deploy_domain }}/current"
    state: link

- name: Force systemd to reread configs
  become: true
  ansible.builtin.systemd:
    daemon_reload: true
