/**
 * Autogenerated by Thrift Compiler (0.22.0)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef PasswordHashing_H
#define PasswordHashing_H

#include <thrift/TDispatchProcessor.h>
#include <thrift/async/TConcurrentClientSyncInfo.h>
#include <memory>
#include "loquat_types.h"

namespace loquat { namespace v1 {

#ifdef _MSC_VER
  #pragma warning( push )
  #pragma warning (disable : 4250 ) //inheriting methods via dominance 
#endif

class PasswordHashingIf {
 public:
  virtual ~PasswordHashingIf() {}
  virtual void sign(std::string& _return, const std::string& password, const int16_t salt_length) = 0;
  virtual void verify(const std::string& code, const std::string& password) = 0;
};

class PasswordHashingIfFactory {
 public:
  typedef PasswordHashingIf Handler;

  virtual ~PasswordHashingIfFactory() {}

  virtual PasswordHashingIf* getHandler(const ::apache::thrift::TConnectionInfo& connInfo) = 0;
  virtual void releaseHandler(PasswordHashingIf* /* handler */) = 0;
  };

class PasswordHashingIfSingletonFactory : virtual public PasswordHashingIfFactory {
 public:
  PasswordHashingIfSingletonFactory(const ::std::shared_ptr<PasswordHashingIf>& iface) : iface_(iface) {}
  virtual ~PasswordHashingIfSingletonFactory() {}

  virtual PasswordHashingIf* getHandler(const ::apache::thrift::TConnectionInfo&) override {
    return iface_.get();
  }
  virtual void releaseHandler(PasswordHashingIf* /* handler */) override {}

 protected:
  ::std::shared_ptr<PasswordHashingIf> iface_;
};

class PasswordHashingNull : virtual public PasswordHashingIf {
 public:
  virtual ~PasswordHashingNull() {}
  void sign(std::string& /* _return */, const std::string& /* password */, const int16_t /* salt_length */) override {
    return;
  }
  void verify(const std::string& /* code */, const std::string& /* password */) override {
    return;
  }
};

typedef struct _PasswordHashing_sign_args__isset {
  _PasswordHashing_sign_args__isset() : password(false), salt_length(false) {}
  bool password :1;
  bool salt_length :1;
} _PasswordHashing_sign_args__isset;

class PasswordHashing_sign_args {
 public:

  PasswordHashing_sign_args(const PasswordHashing_sign_args&);
  PasswordHashing_sign_args& operator=(const PasswordHashing_sign_args&);
  PasswordHashing_sign_args() noexcept;

  virtual ~PasswordHashing_sign_args() noexcept;
  std::string password;
  int16_t salt_length;

  _PasswordHashing_sign_args__isset __isset;

  void __set_password(const std::string& val);

  void __set_salt_length(const int16_t val);

  bool operator == (const PasswordHashing_sign_args & rhs) const;
  bool operator != (const PasswordHashing_sign_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PasswordHashing_sign_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PasswordHashing_sign_pargs {
 public:


  virtual ~PasswordHashing_sign_pargs() noexcept;
  const std::string* password;
  const int16_t* salt_length;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PasswordHashing_sign_result__isset {
  _PasswordHashing_sign_result__isset() : success(false) {}
  bool success :1;
} _PasswordHashing_sign_result__isset;

class PasswordHashing_sign_result {
 public:

  PasswordHashing_sign_result(const PasswordHashing_sign_result&);
  PasswordHashing_sign_result& operator=(const PasswordHashing_sign_result&);
  PasswordHashing_sign_result() noexcept;

  virtual ~PasswordHashing_sign_result() noexcept;
  std::string success;

  _PasswordHashing_sign_result__isset __isset;

  void __set_success(const std::string& val);

  bool operator == (const PasswordHashing_sign_result & rhs) const;
  bool operator != (const PasswordHashing_sign_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PasswordHashing_sign_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};

typedef struct _PasswordHashing_sign_presult__isset {
  _PasswordHashing_sign_presult__isset() : success(false) {}
  bool success :1;
} _PasswordHashing_sign_presult__isset;

class PasswordHashing_sign_presult {
 public:


  virtual ~PasswordHashing_sign_presult() noexcept;
  std::string* success;

  _PasswordHashing_sign_presult__isset __isset;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

typedef struct _PasswordHashing_verify_args__isset {
  _PasswordHashing_verify_args__isset() : code(false), password(false) {}
  bool code :1;
  bool password :1;
} _PasswordHashing_verify_args__isset;

class PasswordHashing_verify_args {
 public:

  PasswordHashing_verify_args(const PasswordHashing_verify_args&);
  PasswordHashing_verify_args& operator=(const PasswordHashing_verify_args&);
  PasswordHashing_verify_args() noexcept;

  virtual ~PasswordHashing_verify_args() noexcept;
  std::string code;
  std::string password;

  _PasswordHashing_verify_args__isset __isset;

  void __set_code(const std::string& val);

  void __set_password(const std::string& val);

  bool operator == (const PasswordHashing_verify_args & rhs) const;
  bool operator != (const PasswordHashing_verify_args &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PasswordHashing_verify_args & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PasswordHashing_verify_pargs {
 public:


  virtual ~PasswordHashing_verify_pargs() noexcept;
  const std::string* code;
  const std::string* password;

  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PasswordHashing_verify_result {
 public:

  PasswordHashing_verify_result(const PasswordHashing_verify_result&) noexcept;
  PasswordHashing_verify_result& operator=(const PasswordHashing_verify_result&) noexcept;
  PasswordHashing_verify_result() noexcept;

  virtual ~PasswordHashing_verify_result() noexcept;

  bool operator == (const PasswordHashing_verify_result & /* rhs */) const;
  bool operator != (const PasswordHashing_verify_result &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const PasswordHashing_verify_result & ) const;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);
  uint32_t write(::apache::thrift::protocol::TProtocol* oprot) const;

};


class PasswordHashing_verify_presult {
 public:


  virtual ~PasswordHashing_verify_presult() noexcept;

  uint32_t read(::apache::thrift::protocol::TProtocol* iprot);

};

class PasswordHashingClient : virtual public PasswordHashingIf {
 public:
  PasswordHashingClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
    setProtocol(prot);
  }
  PasswordHashingClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sign(std::string& _return, const std::string& password, const int16_t salt_length) override;
  void send_sign(const std::string& password, const int16_t salt_length);
  void recv_sign(std::string& _return);
  void verify(const std::string& code, const std::string& password) override;
  void send_verify(const std::string& code, const std::string& password);
  void recv_verify();
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
};

class PasswordHashingProcessor : public ::apache::thrift::TDispatchProcessor {
 protected:
  ::std::shared_ptr<PasswordHashingIf> iface_;
  virtual bool dispatchCall(::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, const std::string& fname, int32_t seqid, void* callContext) override;
 private:
  typedef  void (PasswordHashingProcessor::*ProcessFunction)(int32_t, ::apache::thrift::protocol::TProtocol*, ::apache::thrift::protocol::TProtocol*, void*);
  typedef std::map<std::string, ProcessFunction> ProcessMap;
  ProcessMap processMap_;
  void process_sign(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
  void process_verify(int32_t seqid, ::apache::thrift::protocol::TProtocol* iprot, ::apache::thrift::protocol::TProtocol* oprot, void* callContext);
 public:
  PasswordHashingProcessor(::std::shared_ptr<PasswordHashingIf> iface) :
    iface_(iface) {
    processMap_["sign"] = &PasswordHashingProcessor::process_sign;
    processMap_["verify"] = &PasswordHashingProcessor::process_verify;
  }

  virtual ~PasswordHashingProcessor() {}
};

class PasswordHashingProcessorFactory : public ::apache::thrift::TProcessorFactory {
 public:
  PasswordHashingProcessorFactory(const ::std::shared_ptr< PasswordHashingIfFactory >& handlerFactory) noexcept :
      handlerFactory_(handlerFactory) {}

  ::std::shared_ptr< ::apache::thrift::TProcessor > getProcessor(const ::apache::thrift::TConnectionInfo& connInfo) override;

 protected:
  ::std::shared_ptr< PasswordHashingIfFactory > handlerFactory_;
};

class PasswordHashingMultiface : virtual public PasswordHashingIf {
 public:
  PasswordHashingMultiface(std::vector<std::shared_ptr<PasswordHashingIf> >& ifaces) : ifaces_(ifaces) {
  }
  virtual ~PasswordHashingMultiface() {}
 protected:
  std::vector<std::shared_ptr<PasswordHashingIf> > ifaces_;
  PasswordHashingMultiface() {}
  void add(::std::shared_ptr<PasswordHashingIf> iface) {
    ifaces_.push_back(iface);
  }
 public:
  void sign(std::string& _return, const std::string& password, const int16_t salt_length) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->sign(_return, password, salt_length);
    }
    ifaces_[i]->sign(_return, password, salt_length);
    return;
  }

  void verify(const std::string& code, const std::string& password) override {
    size_t sz = ifaces_.size();
    size_t i = 0;
    for (; i < (sz - 1); ++i) {
      ifaces_[i]->verify(code, password);
    }
    ifaces_[i]->verify(code, password);
  }

};

// The 'concurrent' client is a thread safe client that correctly handles
// out of order responses.  It is slower than the regular client, so should
// only be used when you need to share a connection among multiple threads
class PasswordHashingConcurrentClient : virtual public PasswordHashingIf {
 public:
  PasswordHashingConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(prot);
  }
  PasswordHashingConcurrentClient(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot, std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync) : sync_(sync)
{
    setProtocol(iprot,oprot);
  }
 private:
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> prot) {
  setProtocol(prot,prot);
  }
  void setProtocol(std::shared_ptr< ::apache::thrift::protocol::TProtocol> iprot, std::shared_ptr< ::apache::thrift::protocol::TProtocol> oprot) {
    piprot_=iprot;
    poprot_=oprot;
    iprot_ = iprot.get();
    oprot_ = oprot.get();
  }
 public:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getInputProtocol() {
    return piprot_;
  }
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> getOutputProtocol() {
    return poprot_;
  }
  void sign(std::string& _return, const std::string& password, const int16_t salt_length) override;
  int32_t send_sign(const std::string& password, const int16_t salt_length);
  void recv_sign(std::string& _return, const int32_t seqid);
  void verify(const std::string& code, const std::string& password) override;
  int32_t send_verify(const std::string& code, const std::string& password);
  void recv_verify(const int32_t seqid);
 protected:
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> piprot_;
  std::shared_ptr< ::apache::thrift::protocol::TProtocol> poprot_;
  ::apache::thrift::protocol::TProtocol* iprot_;
  ::apache::thrift::protocol::TProtocol* oprot_;
  std::shared_ptr< ::apache::thrift::async::TConcurrentClientSyncInfo> sync_;
};

#ifdef _MSC_VER
  #pragma warning( pop )
#endif

}} // namespace

#endif
