scalar Time

schema {
  query: Query
  mutation: Mutation
}

type Query {
  version: String!

  indexLog(page: Page!): IndexLogResponse!

  indexHost: [Host!]!
  showHost(id: ID!): Host!

  indexMember: [Member!]!
  showMember(id: ID!): Member!

  indexNetworkInterface: [NetworkInterface!]!
  showNetworkInterface(name: String!): NetworkInterface!

  bondWan: PublicBond!
  bondLan: PrivateBond!
  bondDmz: PrivateBond!
}

type Mutation {
  updateAdministrator(current: Account!, new: Account!): Ok!
  signIn(account: Account!, ttl: Int!): SignInResponse!
  signOut: Ok!

  associateHostWithMember(host: ID!, member: ID!): Ok!
  # dissociateHostFromMember(host: ID!, member: ID!): Ok!
  setHostName(id: ID!, name: String!): Ok!
  blockHost(id: ID!): Ok!
  releaseHost(id: ID!): Ok!
  setHostFixedIp(id: ID!, ip: String): Ok!

  # setNetworkInterfaceMemo(name: String!, memo: String!): Ok!
  # setNetworkInterfacePublicDhcp(name: String!): Ok!
  # setNetworkInterfacePublicStaticIp(
  #   name: String!
  #   address: String!
  #   netmask: String!
  #   gateway: String!
  #   dns1: String!
  #   dns2: String
  # ): Ok!

  bondWan(interfaces: [String!]!): Ok!
  bondLan(interfaces: [String!]!, address: String!): Ok!
  bondDmz(interfaces: [String!]!, address: String!): Ok!

  apply(run: Boolean!): Ok!
  reboot: Ok!
}

type PrivateBond {
  interfaces: [String!]!
  address: String!
}
type PublicBond {
  interfaces: [String!]!
}

type NetworkInterface {
  name: String!
  hardwareAddress: String!
  addresses: [String!]!
  multicastAddresses: [String!]!
  mtu: Int!
  memo: String
}

type Ok {
  createdAt: Time!
}

type Member {
  id: ID!
  sn: String!
  name: String!
  memo: String!
  updatedAt: Time!
}

type Host {
  id: ID!
  name: String
  vendor: String
  mac: String!
  ip: String!
  network: String!
  fixed: Boolean!
  member: Member
  updatedAt: Time!
  deletedAt: Time
}

type SignInResponse {
  username: String!
  token: String!
}

type Log {
  id: ID!
  message: String!
  ip: String!
  createdAt: Time!
}

type IndexLogResponse {
  items: [Log!]!
  pagination: Pagination!
}
input Account {
  name: String!
  password: String!
}
input Page {
  index: Int!
  size: Int!
}

type Pagination {
  index: Int!
  size: Int!
  hasPrevious: Boolean!
  hasNext: Boolean!
  pages: Int!
  total: Int!
}
