// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: bbs.proto
// Protobuf Java Version: 4.29.5

package com.github.saturn_xiv.palm.plugins.bbs.v1;

public interface PostByArticleRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.bbs.v1.PostByArticleRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 article = 1;</code>
   * @return The article.
   */
  int getArticle();

  /**
   * <code>.palm.portal.v1.Page page = 2;</code>
   * @return Whether the page field is set.
   */
  boolean hasPage();
  /**
   * <code>.palm.portal.v1.Page page = 2;</code>
   * @return The page.
   */
  com.github.saturn_xiv.palm.plugins.portal.v1.Page getPage();
  /**
   * <code>.palm.portal.v1.Page page = 2;</code>
   */
  com.github.saturn_xiv.palm.plugins.portal.v1.PageOrBuilder getPageOrBuilder();
}
