// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: wechatpay.proto
// Protobuf Java Version: 4.29.3

package com.github.saturn_xiv.palm.plugins.wechatpay.v1;

public interface WechatPayExecuteBatchTransferRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.wechatpay.v1.WechatPayExecuteBatchTransferRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string app_id = 1;</code>
   * @return The appId.
   */
  java.lang.String getAppId();
  /**
   * <code>string app_id = 1;</code>
   * @return The bytes for appId.
   */
  com.google.protobuf.ByteString
      getAppIdBytes();

  /**
   * <code>.palm.wechatpay.v1.WechatPayExecuteBatchTransferRequest.Batch batch = 2;</code>
   * @return Whether the batch field is set.
   */
  boolean hasBatch();
  /**
   * <code>.palm.wechatpay.v1.WechatPayExecuteBatchTransferRequest.Batch batch = 2;</code>
   * @return The batch.
   */
  com.github.saturn_xiv.palm.plugins.wechatpay.v1.WechatPayExecuteBatchTransferRequest.Batch getBatch();
  /**
   * <code>.palm.wechatpay.v1.WechatPayExecuteBatchTransferRequest.Batch batch = 2;</code>
   */
  com.github.saturn_xiv.palm.plugins.wechatpay.v1.WechatPayExecuteBatchTransferRequest.BatchOrBuilder getBatchOrBuilder();

  /**
   * <code>repeated .palm.wechatpay.v1.WechatPayExecuteBatchTransferRequest.Detail details = 3;</code>
   */
  java.util.List<com.github.saturn_xiv.palm.plugins.wechatpay.v1.WechatPayExecuteBatchTransferRequest.Detail> 
      getDetailsList();
  /**
   * <code>repeated .palm.wechatpay.v1.WechatPayExecuteBatchTransferRequest.Detail details = 3;</code>
   */
  com.github.saturn_xiv.palm.plugins.wechatpay.v1.WechatPayExecuteBatchTransferRequest.Detail getDetails(int index);
  /**
   * <code>repeated .palm.wechatpay.v1.WechatPayExecuteBatchTransferRequest.Detail details = 3;</code>
   */
  int getDetailsCount();
  /**
   * <code>repeated .palm.wechatpay.v1.WechatPayExecuteBatchTransferRequest.Detail details = 3;</code>
   */
  java.util.List<? extends com.github.saturn_xiv.palm.plugins.wechatpay.v1.WechatPayExecuteBatchTransferRequest.DetailOrBuilder> 
      getDetailsOrBuilderList();
  /**
   * <code>repeated .palm.wechatpay.v1.WechatPayExecuteBatchTransferRequest.Detail details = 3;</code>
   */
  com.github.saturn_xiv.palm.plugins.wechatpay.v1.WechatPayExecuteBatchTransferRequest.DetailOrBuilder getDetailsOrBuilder(
      int index);

  /**
   * <code>string scene_id = 9;</code>
   * @return The sceneId.
   */
  java.lang.String getSceneId();
  /**
   * <code>string scene_id = 9;</code>
   * @return The bytes for sceneId.
   */
  com.google.protobuf.ByteString
      getSceneIdBytes();
}
