// Code generated by Thrift Compiler (0.20.0). DO NOT EDIT.

package v1

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"log/slog"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"strings"
	"regexp"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

// Attributes:
//  - To
//  - Body
//  - Callback
type SmsSendTask struct {
  To []string `thrift:"to,1,required" db:"to" json:"to"`
  Body string `thrift:"body,2,required" db:"body" json:"body"`
  // unused fields # 3 to 8
  Callback *string `thrift:"callback,9" db:"callback" json:"callback,omitempty"`
}

func NewSmsSendTask() *SmsSendTask {
  return &SmsSendTask{}
}


func (p *SmsSendTask) GetTo() []string {
  return p.To
}

func (p *SmsSendTask) GetBody() string {
  return p.Body
}
var SmsSendTask_Callback_DEFAULT string
func (p *SmsSendTask) GetCallback() string {
  if !p.IsSetCallback() {
    return SmsSendTask_Callback_DEFAULT
  }
  return *p.Callback
}
func (p *SmsSendTask) IsSetCallback() bool {
  return p.Callback != nil
}

func (p *SmsSendTask) Read(ctx context.Context, iprot thrift.TProtocol) error {
  if _, err := iprot.ReadStructBegin(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
  }

  var issetTo bool = false;
  var issetBody bool = false;

  for {
    _, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
    if err != nil {
      return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
    }
    if fieldTypeId == thrift.STOP { break; }
    switch fieldId {
    case 1:
      if fieldTypeId == thrift.SET {
        if err := p.ReadField1(ctx, iprot); err != nil {
          return err
        }
        issetTo = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 2:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField2(ctx, iprot); err != nil {
          return err
        }
        issetBody = true
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    case 9:
      if fieldTypeId == thrift.STRING {
        if err := p.ReadField9(ctx, iprot); err != nil {
          return err
        }
      } else {
        if err := iprot.Skip(ctx, fieldTypeId); err != nil {
          return err
        }
      }
    default:
      if err := iprot.Skip(ctx, fieldTypeId); err != nil {
        return err
      }
    }
    if err := iprot.ReadFieldEnd(ctx); err != nil {
      return err
    }
  }
  if err := iprot.ReadStructEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
  }
  if !issetTo{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field To is not set"));
  }
  if !issetBody{
    return thrift.NewTProtocolExceptionWithType(thrift.INVALID_DATA, fmt.Errorf("Required field Body is not set"));
  }
  return nil
}

func (p *SmsSendTask)  ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
  _, size, err := iprot.ReadSetBegin(ctx)
  if err != nil {
    return thrift.PrependError("error reading set begin: ", err)
  }
  tSet := make([]string, 0, size)
  p.To =  tSet
  for i := 0; i < size; i ++ {
var _elem0 string
    if v, err := iprot.ReadString(ctx); err != nil {
    return thrift.PrependError("error reading field 0: ", err)
} else {
    _elem0 = v
}
    p.To = append(p.To, _elem0)
  }
  if err := iprot.ReadSetEnd(ctx); err != nil {
    return thrift.PrependError("error reading set end: ", err)
  }
  return nil
}

func (p *SmsSendTask)  ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 2: ", err)
} else {
  p.Body = v
}
  return nil
}

func (p *SmsSendTask)  ReadField9(ctx context.Context, iprot thrift.TProtocol) error {
  if v, err := iprot.ReadString(ctx); err != nil {
  return thrift.PrependError("error reading field 9: ", err)
} else {
  p.Callback = &v
}
  return nil
}

func (p *SmsSendTask) Write(ctx context.Context, oprot thrift.TProtocol) error {
  if err := oprot.WriteStructBegin(ctx, "SmsSendTask"); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err) }
  if p != nil {
    if err := p.writeField1(ctx, oprot); err != nil { return err }
    if err := p.writeField2(ctx, oprot); err != nil { return err }
    if err := p.writeField9(ctx, oprot); err != nil { return err }
  }
  if err := oprot.WriteFieldStop(ctx); err != nil {
    return thrift.PrependError("write field stop error: ", err) }
  if err := oprot.WriteStructEnd(ctx); err != nil {
    return thrift.PrependError("write struct stop error: ", err) }
  return nil
}

func (p *SmsSendTask) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "to", thrift.SET, 1); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:to: ", p), err) }
  if err := oprot.WriteSetBegin(ctx, thrift.STRING, len(p.To)); err != nil {
    return thrift.PrependError("error writing set begin: ", err)
  }
  for i := 0; i<len(p.To); i++ {
    for j := i+1; j<len(p.To); j++ {
      if func(tgt, src string) bool {
        if tgt != src { return false }
        return true
      }(p.To[i], p.To[j]) {
        return thrift.PrependError("", fmt.Errorf("%T error writing set field: slice is not unique", p.To))
      }
    }
  }
  for _, v := range p.To {
    if err := oprot.WriteString(ctx, string(v)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err) }
  }
  if err := oprot.WriteSetEnd(ctx); err != nil {
    return thrift.PrependError("error writing set end: ", err)
  }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 1:to: ", p), err) }
  return err
}

func (p *SmsSendTask) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if err := oprot.WriteFieldBegin(ctx, "body", thrift.STRING, 2); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:body: ", p), err) }
  if err := oprot.WriteString(ctx, string(p.Body)); err != nil {
  return thrift.PrependError(fmt.Sprintf("%T.body (2) field write error: ", p), err) }
  if err := oprot.WriteFieldEnd(ctx); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T write field end error 2:body: ", p), err) }
  return err
}

func (p *SmsSendTask) writeField9(ctx context.Context, oprot thrift.TProtocol) (err error) {
  if p.IsSetCallback() {
    if err := oprot.WriteFieldBegin(ctx, "callback", thrift.STRING, 9); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field begin error 9:callback: ", p), err) }
    if err := oprot.WriteString(ctx, string(*p.Callback)); err != nil {
    return thrift.PrependError(fmt.Sprintf("%T.callback (9) field write error: ", p), err) }
    if err := oprot.WriteFieldEnd(ctx); err != nil {
      return thrift.PrependError(fmt.Sprintf("%T write field end error 9:callback: ", p), err) }
  }
  return err
}

func (p *SmsSendTask) Equals(other *SmsSendTask) bool {
  if p == other {
    return true
  } else if p == nil || other == nil {
    return false
  }
  if len(p.To) != len(other.To) { return false }
  for i, _tgt := range p.To {
    _src1 := other.To[i]
    if _tgt != _src1 { return false }
  }
  if p.Body != other.Body { return false }
  if p.Callback != other.Callback {
    if p.Callback == nil || other.Callback == nil {
      return false
    }
    if (*p.Callback) != (*other.Callback) { return false }
  }
  return true
}

func (p *SmsSendTask) String() string {
  if p == nil {
    return "<nil>"
  }
  return fmt.Sprintf("SmsSendTask(%+v)", *p)
}

func (p *SmsSendTask) LogValue() slog.Value {
  if p == nil {
    return slog.AnyValue(nil)
  }
  v := thrift.SlogTStructWrapper{
    Type: "*v1.SmsSendTask",
    Value: p,
  }
  return slog.AnyValue(v)
}

var _ slog.LogValuer = (*SmsSendTask)(nil)

func (p *SmsSendTask) Validate() error {
  return nil
}
