server:
  port: 11003
spring:
  grpc:
    server:
      port: 11004
  datasource:
    url: jdbc:postgresql://localhost:5432/marigold_dev
    username: www
    password: "change-me"
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
