[package]
name = "marigold"
version = "2026.3.29"
edition = "2024"
description = "A total free online education solution."
homepage = "https://github.com/saturn-xiv/palm"

[dependencies]
tokio-stream = "0.1"
futures = "0.3"
log = "0.4"
juniper_graphql_ws = "0.5"
axum = "0.8"
grpc = "0.9"
env_logger = "0.11"
askama = "0.16"
juniper = "0.17"
hyper = "1"
protobuf = "3"

[dependencies.juniper_axum]
version = "0.3"
features = ["subscriptions"]

[dependencies.tower-http]
version = "0.6"
features = ["fs"]

[dependencies.reqwest]
version = "0.13"
features = ["json"]

[dependencies.strum]
version = "0.28"
features = ["derive"]

[dependencies.nix]
version = "0.31"
features = ["user"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.tokio]
version = "1"
features = ["full"]

[dependencies.diesel]
version = "2"
default-features = false

[dependencies.clap]
version = "4"
features = ["derive"]

[dependencies.phlox]
path = "../phlox"

[build-dependencies]
grpc-protobuf-build = "0.9"
