syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.github.saturn_xiv.palm.plugins.crypto.v1";
option java_outer_classname = "CryptoProto";
option go_package = "./;v2";
option csharp_namespace = "Palm.Plugins.Crypto.Grpc";
package palm.crypto.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/duration.proto";

service Aead {
  rpc Encrypt(AeadEncryptRequest) returns (AeadEncryptResponse) {}
  rpc Decrypt(AeadDecryptRequest) returns (AeadDecryptResponse) {}
}

message AeadEncryptRequest {
  bytes plain = 1;
  bytes associated = 2;
}
message AeadEncryptResponse {
  bytes cipher = 1;
}
message AeadDecryptRequest {
  bytes cipher = 1;
  bytes associated = 2;
}
message AeadDecryptResponse {
  bytes plain = 1;
}

// ----------------------------------------------------------------------------
service HMac {
  rpc Compute(HMacComputeRequest) returns (HMacComputeResponse) {}
  rpc Verify(HMacVerifyRequest) returns (google.protobuf.Empty) {}
}
message HMacComputeRequest {
  bytes data = 1;
}
message HMacComputeResponse {
  bytes mac = 1;
}
message HMacVerifyRequest {
  bytes mac = 1;
  bytes data = 2;
}

// ----------------------------------------------------------------------------
service Jwt {
  rpc Sign(JwtSignRequest) returns (JwtSignResponse) {}
  rpc Verify(JwtVerifyRequest) returns (JwtVerifyResponse) {}
}
message JwtSignRequest {
  string issuer = 1;
  string subject = 2;
  repeated string audiences = 3;
  google.protobuf.Duration ttl = 4;
}
message JwtSignResponse {
  string token = 1;
}
message JwtVerifyRequest {
  string token = 1;
  string issuer = 2;
  string audience = 3;
}
message JwtVerifyResponse {
  string id = 1;
  string subject = 2;
}
