syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.github.saturn_xiv.palm.plugins.portal.v1";
option java_outer_classname = "PortalProto";
option go_package = "./;v2";
option csharp_namespace = "Palm.Plugins.Portal.Grpc";
package palm.portal.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/duration.proto";

message IdRequest {
  int64 id = 1;
}

message Page {
  int64 index = 1;
  int64 size  = 2;
}

message Pagination {
  Page  current      = 1;
  bool  has_previous = 2;
  bool  has_next     = 3;
  int64 pages        = 4;
  int64 total        = 5;
}

message File  {
  string bucket = 1;
  string object = 2;
}

message RichText {
  enum Editor {
    CK_EDITOR = 0;
  }
  Editor        editor      = 1;
  string        body        = 2;
  repeated File attachments = 3;
}

message Location {
  enum Map {
    GOOGLE = 0;
  }
  Map    map     = 1;
  string address = 2;
}

// ----------------------------------------------------------------------------
service Locale{
  rpc Index(Page) returns (LocaleIndexResponse){}
  rpc Set(LocaleSetRequest) returns (google.protobuf.Empty) {}
  rpc ByLang(LocaleByLangRequest) returns (LocaleByLangResponse) {}
  rpc Destroy(IdRequest) returns (google.protobuf.Empty){}
}

message LocaleSetRequest {
  string lang    = 1;
  string code    = 2;
  string message = 3;
}

message LocaleByLangRequest {
  string lang = 1;
}

message LocaleByLangResponse {
  repeated LocaleIndexResponse.Item items = 1;
}

message LocaleIndexResponse{
  message Item {
    int64                     id         = 1;
    string                    lang       = 2;
    string                    code       = 3;
    string                    message    = 4;
    google.protobuf.Timestamp updated_at = 9;
  }
  repeated Item items      = 1;
  Pagination    pagination = 9;
}

// ----------------------------------------------------------------------------

service Site {
  rpc Currencies(google.protobuf.Empty) returns (CurrenciesResponse) {}
}

message CurrenciesResponse {
  message Item {
    string          code    = 1;
    string          name    = 2;
    string          country = 3;
    uint32          number  = 4;
    optional uint32 units   = 5;
    optional bool   is_fund = 6;
  }
  repeated Item items = 1;
}

// ----------------------------------------------------------------------------
service EmailUser{
  rpc Index(Page) returns (EmailUserIndexResponse) {}
  rpc Destroy(IdRequest) returns (google.protobuf.Empty){}
  rpc Confirm(IdRequest) returns (google.protobuf.Empty){}
  rpc SetPassword(EmailUserSetPasswordRequest) returns (google.protobuf.Empty){}

  rpc SignUp(EmailUserSignUpRequest) returns (google.protobuf.Empty){}
  rpc SignIn(EmailUserSignInRequest) returns (UserSignInResponse){}
  rpc UnlockByEmail(EmailUserUnlockByEmailRequest) returns (google.protobuf.Empty){}
  rpc UnlockByToken(EmailUserUnlockByTokenRequest) returns (google.protobuf.Empty){}
  rpc ConfirmByEmail(EmailUserConfirmByEmailRequest) returns (google.protobuf.Empty){}
  rpc ConfirmByToken(EmailUserConfirmByTokenRequest) returns (google.protobuf.Empty){}
  rpc ForgotPassword(EmailUserForgotPasswordRequest) returns (google.protobuf.Empty){}
  rpc ResetPassword(EmailUserResetPasswordRequest) returns (google.protobuf.Empty){}

  rpc SetName(EmailUserSetNameRequest) returns (google.protobuf.Empty){}
  rpc SetAvatar(EmailUserSetAvatarRequest) returns (google.protobuf.Empty){}
  rpc ChangePassword(EmailUserChangePasswordRequest) returns (google.protobuf.Empty){}
}

message EmailUserSignInRequest {
  string email    = 1;
  string password = 2;
}

message EmailUserSignUpRequest {
  string name     = 1;
  string email    = 2;
  string password = 3;
  string lang     = 8;
  string timezone = 9;
  string home     = 99;
}

message EmailUserUnlockByEmailRequest {
  string email = 1;
  string home  = 99;
}

message EmailUserUnlockByTokenRequest {
  string token = 1;
}

message EmailUserConfirmByEmailRequest {
  string email = 1;
  string home  = 99;
}

message EmailUserConfirmByTokenRequest {
  string token = 1;
}

message EmailUserForgotPasswordRequest {
  string email = 1;
  string home  = 99;
}

message EmailUserResetPasswordRequest {
  string token    = 1;
  string password = 2;
}

message EmailUserSetNameRequest {
  string name = 1;
}

message EmailUserSetAvatarRequest {
  oneof by  {
    string url  = 1;
    File   file = 2;
  }
}

message EmailUserChangePasswordRequest {
  string current_password = 1;
  string new_password     = 2;
}

message EmailUserIndexResponse{
  message Item {
    int64                              id           = 1;
    string                             email        = 2;
    string                             name         = 3;
    optional string                    avatar       = 16;
    optional google.protobuf.Timestamp confirmed_at = 17;
    optional google.protobuf.Timestamp deleted_at   = 18;
    google.protobuf.Timestamp          updated_at   = 19;
    UserIndexResponse.Item             user         = 99;
  }
  repeated Item items      = 1;
  Pagination    pagination = 9;
}

message EmailUserSetPasswordRequest{
  int64  id       = 1;
  string password = 2;
}
// ----------------------------------------------------------------------------

service User {
  rpc Index(Page) returns (UserIndexResponse){}
  rpc Destroy(IdRequest) returns (google.protobuf.Empty){}
  rpc Lock(IdRequest) returns (google.protobuf.Empty){}
  rpc Unlock(IdRequest) returns (google.protobuf.Empty){}

  rpc IndexAttachment(Page) returns (UserIndexAttachmentResponse){}
  rpc CreateAttachment(UserCreateAttachmentRequest)returns (UserCreateAttachmentUploadResponse){}
  rpc ShowAttachment(UserShowAttachmentRequest) returns (UserShowAttachmentResponse){}
  rpc SetAttachmentUploaded(IdRequest) returns (google.protobuf.Empty){}
  rpc SetAttachmentTitle(UserSetAttachmentTitleRequest) returns (google.protobuf.Empty){}
  rpc DestroyAttachment(IdRequest) returns (google.protobuf.Empty){}

  rpc IndexLog(Page) returns (UserIndexLogResponse) {}
  rpc SetLang(UserSetLangRequest) returns (google.protobuf.Empty){}
  rpc SetTimezone(UserSetTimezoneRequest) returns (google.protobuf.Empty){}
}

message UserSetLangRequest {
  string lang = 1;
}

message UserSetTimezoneRequest {
  string timezone = 1;
}

message UserIndexResponse {
  message Item {
    int64                              id                   = 1;
    string                             sn                   = 2;
    string                             lang                 = 3;
    string                             timezone             = 4;
    int64                              signed_in_total      = 11;
    optional google.protobuf.Timestamp current_signed_in_at = 12;
    optional string                    current_signed_in_ip = 13;
    optional google.protobuf.Timestamp last_signed_in_at    = 14;
    optional string                    last_signed_in_ip    = 15;
    optional google.protobuf.Timestamp locked_at            = 17;
    optional google.protobuf.Timestamp deleted_at           = 18;
    google.protobuf.Timestamp          updated_at           = 19;
  }
  repeated Item items      = 1;
  Pagination    pagination = 9;
}

message UserSetAttachmentTitleRequest {
  int64  id    = 1;
  string title = 2;
}

message UserShowAttachmentRequest {
  int64                             id       = 1;
  bool                              download = 2;
  optional google.protobuf.Duration ttl      = 9;
}

message UserShowAttachmentResponse{
  string url = 1;
}

message UserCreateAttachmentRequest {
  string                   title             = 1;
  string                   content_type      = 2;
  uint64                   size              = 3;
  optional uint32          expire_after_days = 4;
  bool                     public            = 5;
  google.protobuf.Duration ttl               = 9;
}

message UserCreateAttachmentUploadResponse {
  string                           url  = 1;
  UserIndexAttachmentResponse.Item item = 2;
}

message UserIndexAttachmentResponse{
  message Item{
    int64                              id                = 1;
    string                             bucket            = 2;
    string                             object            = 3;
    string                             title             = 4;
    string                             content_type      = 5;
    uint64                             size              = 6;
    optional google.protobuf.Timestamp uploaded_at       = 7;
    optional uint32                    expire_after_days = 8;
    bool                               public            = 9;
    google.protobuf.Timestamp          updated_at        = 19;
  }
  repeated Item items      = 1;
  Pagination    pagination = 2;
}

message UserIndexLogResponse {
  message Item{
    enum Level {
      DEBUG   = 0;
      INFO    = 1;
      WARNING = 2;
      ERROR   = 3;
    }
    int64                     id         = 1;
    string                    plugin     = 2;
    string                    ip         = 3;
    Level                     level      = 4;
    string                    message    = 5;
    google.protobuf.Timestamp created_at = 9;
  }
  repeated Item items      = 1;
  Pagination    pagination = 9;
}

message Session {
  enum ProviderType {
    EMAIL               = 0;
    PHONE               = 1;
    GOOGLE_OAUTH2       = 2;
    WECHAT_OAUTH2       = 3;
    WECHAT_MINI_PROGRAM = 4;
  }
  message Subject{
    ProviderType type = 1;
    string       sn   = 2;
  }
  Subject                subject   = 1;
  string                 name      = 2;
  string                 avatar    = 3;
  UserIndexResponse.Item user      = 8;
  string                 client_ip = 9;
}

message UserSignInResponse {
  string token = 1;
}
// ----------------------------------------------------------------------------
