syntax = "proto3";

option java_multiple_files = true;
option java_package = "com.github.saturn_xiv.palm.plugins.s3.v1";
option java_outer_classname = "S3Proto";
option go_package = "./;v2";
option csharp_namespace = "Palm.Plugins.S3.Grpc";
package palm.s3.v1;

import "google/protobuf/empty.proto";
import "google/protobuf/duration.proto";
import "google/protobuf/timestamp.proto";

service S3 {
  rpc MakeBucket(MakeBucketRequest) returns (google.protobuf.Empty) {}
  rpc BucketExists(BucketExistsRequest) returns (BucketExistsResponse) {}
  rpc ListBucket(google.protobuf.Empty) returns (ListBucketResponse) {}
  rpc PresignedPutObject(PresignedPutObjectRequest) returns (PresignedPutObjectResponse) {}
  rpc RemoveObject(RemoveObjectRequest) returns (google.protobuf.Empty) {}
  rpc PresignedGetObject(PresignedGetObjectRequest) returns (PresignedGetObjectResponse) {}
  rpc GetObject(GetObjectRequest) returns (GetObjectResponse) {}
  rpc StatObject(StatObjectRequest) returns (StatObjectResponse) {}
}

message StatObjectRequest{
  string bucket = 1;
  string object = 2;
}

message StatObjectResponse {
  int64                     size          = 1;
  string                    content_type  = 2;
  string                    version_id    = 3;
  google.protobuf.Timestamp last_modified = 4;
  google.protobuf.Timestamp expires       = 5;
}

message GetObjectRequest{
  string bucket = 1;
  string object = 2;
}

message GetObjectResponse {
  string url = 1;
}

message PresignedGetObjectRequest {
  string                   bucket = 1;
  string                   object = 2;
  optional string          title  = 3;
  google.protobuf.Duration ttl    = 9;
}

message PresignedGetObjectResponse{
  string url = 1;
}

message RemoveObjectRequest {
  string bucket = 1;
  string object = 2;
}

message MakeBucketRequest {
  string          name              = 1;
  bool            public            = 2;
  optional uint32 expire_after_days = 3;
}

message BucketExistsRequest {
  string name = 1;
}

message BucketExistsResponse {
  bool exists = 1;
}

message PresignedPutObjectRequest {
  string                   bucket = 1;
  string                   object = 2;
  google.protobuf.Duration ttl    = 9;
}

message PresignedPutObjectResponse {
  string url = 1;
}

message ListBucketResponse {
  message Item {
    string name = 1;
  }
  repeated Item items = 1;
}
