// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: dictionary.proto
// Protobuf Java Version: 4.29.5

package com.github.saturn_xiv.palm.plugins.dictionary.v1;

public interface DirectorySearchRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.dictionary.v1.DirectorySearchRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string keywords = 1;</code>
   * @return A list containing the keywords.
   */
  java.util.List<java.lang.String>
      getKeywordsList();
  /**
   * <code>repeated string keywords = 1;</code>
   * @return The count of keywords.
   */
  int getKeywordsCount();
  /**
   * <code>repeated string keywords = 1;</code>
   * @param index The index of the element to return.
   * @return The keywords at the given index.
   */
  java.lang.String getKeywords(int index);
  /**
   * <code>repeated string keywords = 1;</code>
   * @param index The index of the value to return.
   * @return The bytes of the keywords at the given index.
   */
  com.google.protobuf.ByteString
      getKeywordsBytes(int index);
}
