scalar Time

schema {
  query: Query
  mutation: Mutation
}

type Query {
  version: String!

  forgotEmailUserPassword(home: String!, email: String!): Ok!
  confirmEmailUser(home: String!, email: String!): Ok!
  unlockEmailUser(home: String!, email: String!): Ok!

  # confirmUserByPhone(phone: String!): Ok!
  # unlockUserByPhone(home: String!, email: String!): Ok!

  getGoogleOauth2Url(home: String!, sessionId: String!): String!

  # indexUser(page: Page!): IndexUserResponse!
  indexLog(page: Page!): IndexLogResponse!
  # refresh: RefreshResponse!

  indexAttachment(page: Page!): IndexAttachmentResponse!
  showAttachment(id: ID!): Attachment!

  indexLocale(page: Page!): IndexLocaleResponse!
  getLocaleByLang(lang: String!): [Locale!]!

  currencies: [Currency!]!
}

type Mutation {
  signInByEmail(
    email: String!
    password: String!
    ttl: Int!
  ): UserSignInResponse!
  # signInByPhone(phone: String!, password: String!, ttl: Int!): UserSignInResponse!
  signInByGoogleOauth2(
    home: String!
    sessionId: String!
    code: String!
    state: String!
    lang: String!
    timezone: String!
    ttl: Int!
  ): UserSignInResponse!
  # signInByWechatOauth2(token: String!): SignInResponse!
  # signInByWechatMiniProgram(token: String!): SignInResponse!
  # changeEmailUserPassword(currentPassword: String!, newPassword: String!): Ok!
  # resetEmailUserPassword(token: String!, password: String!): Ok!

  # signOut: Ok!
  setEmailUserName(name: String!): Ok!
  setEmailUserAvatar(avatar: String!): Ok!
  changeEmailUserPassword(currentPassword: String!, newPassword: String!): Ok!
  setUserLocation(lang: String!, timezone: String!): Ok!
  # confirmEmailUser(token: String!): Ok!
  # unlockEmailUser(token: String!): Ok!

  lockUser(id: ID!, reason: String!): Ok!
  unlockUser(id: ID!, reason: String!): Ok!
  destroyUser(id: ID!, reason: String!): Ok!
  # setEmailUserPassword(id: ID!, password: String!, reason: String!): Ok!
  # setPhoneUserPassword(id: ID!, password: String!, reason: String!): Ok!

  createAttachment(
    title: String!
    contentType: String!
    size: Int!
    public: Boolean!
    expireAfterDays: Int
    ttl: Int!
  ): String!
  setAttachmentUploaded(id: ID!): Ok!
  setAttachmentTitle(id: ID!, title: String!): Ok!
  # associateAttachment(
  #   attachmentId: ID!
  #   resourceType: String!
  #   resourceId: ID
  # ): Ok!
  # dissociateAttachment(
  #   attachmentId: ID!
  #   resourceType: String!
  #   resourceId: ID
  # ): Ok!
  destroyAttachment(id: ID!): Ok!

  # siteSetFavicon(url: String!): Ok!
  # siteSetMaintenanceMode(ok: Boolean!, reason: String!): Ok!
  # siteSetDetails(lang: String!, form: SiteDetailsForm!): Ok!
  # siteSetReCaptcha(siteKey: String!, enable: Boolean!): Ok!
  # siteSetGoogleSiteVerify(siteId: String!, enable: Boolean!): Ok!
  # siteSetBaiduSiteVerify(siteId: String, enable: Boolean!): Ok!
  # siteSetIndexNow(key: String, enable: Boolean): Ok!

  setLocale(lang: String!, code: String!, message: String!): Ok!
  destroyLocale(id: ID!): Ok!
}

type Attachment {
  id: ID!
  title: String!
  bucket: String!
  object: String!
  contentType: String!
  public: Boolean!
  size: Int!
  uploadedAt: Time
  updatedAt: Time!
  resources: [Resource!]!
}
type IndexAttachmentResponse {
  items: [Attachment!]!
  pagination: Pagination!
}
input SiteDetailsForm {
  title: String!
  subhead: String!
  keywords: [String!]!
  description: String!
  copyright: String!
}

type IndexUserResponse {
  items: [User!]!
  pagination: Pagination!
}

type Log {
  id: ID!
  plugin: String!
  ip: String!
  level: Int!
  message: String!
  createdAt: Time!
}
type IndexLogResponse {
  items: [Log!]!
  pagination: Pagination!
}

type Locale {
  id: ID!
  lang: String!
  code: String!
  message: String!
  updatedAt: Time!
}
type IndexLocaleResponse {
  items: [Locale!]!
  pagination: Pagination!
}

type Ok {
  createdAt: Time!
}
input Page {
  index: Int!
  size: Int!
}

type Pagination {
  index: Int!
  size: Int!
  hasPrevious: Boolean!
  hasNext: Boolean!
  pages: Int!
  total: Int!
}
type Resource {
  type: String!
  id: ID
}
type Permission {
  resource: Resource!
  operation: String!
}

type Site {
  favicon: String!
  title: String!
  subhead: String!
  keywords: [String!]!
  description: String!
  copyright: String!
}
type RefreshResponse {
  lang: String!
  timezone: String!
  username: String!
  site: Site!
  roles: [String!]!
  permissions: [Permission!]!
}
type UserSignInResponse {
  token: String!
  # layout: RefreshResponse!
}
type UserDetail {
  id: ID!
  sn: String!
  lang: String!
  timezone: String!
  lockedAt: Time
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!
}
type EmailUser {
  id: ID!
  user: UserDetail!
  name: String!
  email: String!
  confirmedAt: Time
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!
}
type SmsUser {
  id: ID!
  user: UserDetail!
  name: String!
  phone: String!
  confirmedAt: Time
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!
}
type GoogleOauth2User {
  id: ID!
  user: UserDetail!
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!
}
type WechatOauth2User {
  id: ID!
  user: UserDetail!
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!
}
type WechatMiniProgramUser {
  id: ID!
  user: UserDetail!
  deletedAt: Time
  updatedAt: Time!
  createdAt: Time!
}
union User =
  | EmailUser
  | SmsUser
  | GoogleOauth2User
  | WechatOauth2User
  | WechatMiniProgramUser
type Currency {
  code: String!
  name: String!
  country: String!
  isFund: Boolean
  number: Int!
}
