/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RecordingEnumSource : How the recording was created. Can be: `DialVerb`, `Conference`, `OutboundAPI`, `Trunking`, `RecordVerb`, `StartCallRecordingAPI`, and `StartConferenceRecordingAPI`.
/// How the recording was created. Can be: `DialVerb`, `Conference`, `OutboundAPI`, `Trunking`, `RecordVerb`, `StartCallRecordingAPI`, and `StartConferenceRecordingAPI`.
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum RecordingEnumSource {
    #[serde(rename = "DialVerb")]
    DialVerb,
    #[serde(rename = "Conference")]
    Conference,
    #[serde(rename = "OutboundAPI")]
    OutboundApi,
    #[serde(rename = "Trunking")]
    Trunking,
    #[serde(rename = "RecordVerb")]
    RecordVerb,
    #[serde(rename = "StartCallRecordingAPI")]
    StartCallRecordingApi,
    #[serde(rename = "StartConferenceRecordingAPI")]
    StartConferenceRecordingApi,
}

impl std::fmt::Display for RecordingEnumSource {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::DialVerb => write!(f, "DialVerb"),
            Self::Conference => write!(f, "Conference"),
            Self::OutboundApi => write!(f, "OutboundAPI"),
            Self::Trunking => write!(f, "Trunking"),
            Self::RecordVerb => write!(f, "RecordVerb"),
            Self::StartCallRecordingApi => write!(f, "StartCallRecordingAPI"),
            Self::StartConferenceRecordingApi => write!(f, "StartConferenceRecordingAPI"),
        }
    }
}

impl Default for RecordingEnumSource {
    fn default() -> RecordingEnumSource {
        Self::DialVerb
    }
}
