# https://pip.pypa.io/en/stable/installation/
- name: Download get-pip
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: "{{ app_downloads }}/get-pip.py"
    mode: "0644"

- name: Run get-pip
  ansible.builtin.command: "python3 {{ app_downloads }}/get-pip.py"
  args:
    creates: "{{ ansible_env.HOME }}/.local/bin/pip"

# - name: Install python packages
#   pip:
#     name:
#       - cmake
#     extra_args: --user
#     executable: pip3
