-- migrate:up
CREATE TABLE users(
    id SERIAL PRIMARY KEY,
    name VARCHAR(31) NOT NULL,
    password VARCHAR(255) NOT NULL,
    "version" INT NOT NULL DEFAULT 0,
    updated_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE UNIQUE INDEX idx_users_name ON users(name);
CREATE TABLE logs(
    id SERIAL PRIMARY KEY,
    user_id INTEGER NOT NULL,
    message TEXT NOT NULL,
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
-- migrate:down
DROP TABLE logs;
DROP TABLE users;
