---
logging:
  level: INFO
  loggers:
    com.github.saturn_xiv: DEBUG
atropa:
  host: 192.168.0.10
  port: 10001
  key-file: tmp/atropa-client.key
  cert-file: tmp/atropa-client.crt
  ca-file: tmp/ca.crt
  authority: "www.saturn-xiv.org"
