// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: s3.proto
// Protobuf Java Version: 4.29.5

package com.github.saturn_xiv.palm.plugins.s3.v1;

public interface GetObjectRetentionResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.s3.v1.GetObjectRetentionResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string retention_mode = 1;</code>
   * @return The retentionMode.
   */
  java.lang.String getRetentionMode();
  /**
   * <code>string retention_mode = 1;</code>
   * @return The bytes for retentionMode.
   */
  com.google.protobuf.ByteString
      getRetentionModeBytes();

  /**
   * <code>.google.protobuf.Timestamp retain_until_date = 2;</code>
   * @return Whether the retainUntilDate field is set.
   */
  boolean hasRetainUntilDate();
  /**
   * <code>.google.protobuf.Timestamp retain_until_date = 2;</code>
   * @return The retainUntilDate.
   */
  com.google.protobuf.Timestamp getRetainUntilDate();
  /**
   * <code>.google.protobuf.Timestamp retain_until_date = 2;</code>
   */
  com.google.protobuf.TimestampOrBuilder getRetainUntilDateOrBuilder();
}
