// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: s3.proto
// Protobuf Java Version: 4.31.1

package com.github.saturn_xiv.palm.plugins.s3.v1;

@com.google.protobuf.Generated
public interface PresignedGetObjectRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:palm.s3.v1.PresignedGetObjectRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string bucket = 1;</code>
   * @return The bucket.
   */
  java.lang.String getBucket();
  /**
   * <code>string bucket = 1;</code>
   * @return The bytes for bucket.
   */
  com.google.protobuf.ByteString
      getBucketBytes();

  /**
   * <code>string object = 2;</code>
   * @return The object.
   */
  java.lang.String getObject();
  /**
   * <code>string object = 2;</code>
   * @return The bytes for object.
   */
  com.google.protobuf.ByteString
      getObjectBytes();

  /**
   * <code>optional string title = 3;</code>
   * @return Whether the title field is set.
   */
  boolean hasTitle();
  /**
   * <code>optional string title = 3;</code>
   * @return The title.
   */
  java.lang.String getTitle();
  /**
   * <code>optional string title = 3;</code>
   * @return The bytes for title.
   */
  com.google.protobuf.ByteString
      getTitleBytes();

  /**
   * <code>.google.protobuf.Duration ttl = 9;</code>
   * @return Whether the ttl field is set.
   */
  boolean hasTtl();
  /**
   * <code>.google.protobuf.Duration ttl = 9;</code>
   * @return The ttl.
   */
  com.google.protobuf.Duration getTtl();
  /**
   * <code>.google.protobuf.Duration ttl = 9;</code>
   */
  com.google.protobuf.DurationOrBuilder getTtlOrBuilder();
}
